### ISSUE TITLE
gradle please?

### ISSUE THREAD

**Issue by Swisyn** [cymcsg/UltimateRecyclerView#1]
Thank you for amazing lib!

I'd like to use it in one of my project, could you host it in maven please?

**Comment by cymcsg** [comment]
Thank you for using Ultimate Recyclerview. I'll try to host it in ``jcenter`` this week when I fix most bugs in current version.You can watch the repository.

In addition,I think it is a good idea for you to fork the repository and not to clone the repository and push it.

**Comment by Swisyn** [comment]
Thank you so much for quick reply. Actually it's good to upload it as beta to start using. I've cloned it to host in maven myself but now i forked it.

**Comment by cymcsg** [comment]
Thank you.Now you can use
```groovy
repositories {
        jcenter()
    }
dependencies {
    ...
    compile 'com.marshalchen.ultimaterecyclerview:library:0.1.0'
}
```

to include the lib.
