### ISSUE TITLE
Request : Ability pullToRefresh in empty Recyclerview

### ISSUE THREAD

**Issue by choiruru** [cymcsg/UltimateRecyclerView#10]
hi **cymcsg**, its a great library and very helpfull.
I just try pulltorefresh when adapter is empty, and it seems does'nt work anyway.
maybe you can change pulltorefresh with **MultiSwipeRefreshLayout**
here is the link : [MultiSwipeRefreshLayout.java](https://developer.android.com/samples/SwipeRefreshMultipleViews/src/com.example.android.swiperefreshmultipleviews/MultiSwipeRefreshLayout.html)
and you can add **layout_empty.xml** with scrollview as parent view to make it enable to pulltorefresh.

thanks **cymcsg** :+1:

**Comment by choiruru** [comment]
hi **cymcsg**, my problem is solved.
there are error from my code that make empty view can't be refresh.
sorry for my mistake

**Comment by ysy950803** [comment]
How do you solve it? #319 
I have a problem that I cannot see the refresh circle.

**Comment by choiruru** [comment]
hi @ysy950803 : have you try empty view with ScrollView as parent view..??

**Comment by ysy950803** [comment]
@choiruru I have solved it with using adapter and data, finally the problems dismiss, but I don't understand specific reasons about it.
