### ISSUE TITLE
loading more scroll back [bug]

### ISSUE THREAD

**Issue by jjhesk** [cymcsg/UltimateRecyclerView#100]
there is an issue when the loading more is under process and scrolling the recyclerview to top. It does not allow or laggy while doing so. Do you get the same issue? I think it is also related to #28 , #71 , #87, #96 , #81 

- [x] sometimes it will be laggy with im using setchangedatasetnotified
- [x] appear and disappear will affect the first child view to be recycled when the parallax header is in use. Looking into method ```enableShoworHideToolbarAndFloatingButton```  [noted](https://github.com/cymcsg/UltimateRecyclerView/blob/dev/UltimateRecyclerView/ultimaterecyclerview/src/main/java/com/marshalchen/ultimaterecyclerview/UltimateRecyclerView.java#L358)
- [x] disableLoadmore and enableLoadmore repeatitively
- [x] the custom loading more layout logics for grid layout. How does it support the custom loading layout to be appears on the very bottom of the section?

**Comment by jjhesk** [comment]
By the way, why do we need to have CHANGED_FOOTER and FOOTER in the [adapter](https://github.com/cymcsg/UltimateRecyclerView/blob/master/UltimateRecyclerView/ultimaterecyclerview/src/main/java/com/marshalchen/ultimaterecyclerview/UltimateViewAdapter.java)

**Comment by cymcsg** [comment]
Do you think we need only one of them?

**Comment by jjhesk** [comment]
I just dont get why you would go with two flag. They are ultimately serving the same function and that flag will just create a tree-some of bugs after all. I think the effective why is to drop to only one flag.

**Comment by jjhesk** [comment]
@cymcsg Does it support with grid layout? the custom loading more layout logics for grid layout. How does it support the custom loading layout to be appears on the very bottom of the section and it is preferred at the horizontal center that can span over the valuable of the column count?

**Comment by cymcsg** [comment]
In the current version , the loading more feature do not support properly.The loading more view will only be set as a item of adapter.I think it would be adapted to GridLayout and StaggeredGridLayout.

**Comment by jjhesk** [comment]
is that possible to make it spanned across columns?

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.
