### ISSUE TITLE
How disable headerview

### ISSUE THREAD

**Issue by Radzhab** [cymcsg/UltimateRecyclerView#108]
I dont need in my project headerview. How i can disable it in adapter?

**Comment by cymcsg** [comment]
Do you mean sticky header or the header of recyclerview?
Both of them need to be defined in your code in your need them.If you do not need them,you can remove ``ultimateRecyclerView.setParallaxHeader`` or `` ultimateRecyclerView.addItemDecoration(headersDecor);`` easily.
