### ISSUE TITLE
setSwipeToDismissCallback stopped working in 0.3.7

### ISSUE THREAD

**Issue by Jdruwe** [cymcsg/UltimateRecyclerView#109]
I've upgraded from 0.3.4 and the setSwipeToDismissCallback is not recognized anymore. Is this a bug or am I doing something wrong?

**Comment by jjhesk** [comment]
there we have alot of changes and arrangments from the previous version. u might need to look into the demo code and figure it out.

**Comment by cymcsg** [comment]
The latest version(0.3.9) change to an other way to achieve the feature for better support the latest version of Recyclerview. Maybe it is not very good to change the api but it's helpful to improve the performance.

**Comment by Jdruwe** [comment]
A better documentation would come in handy :S It is really hard to find how it's done now.

**Comment by cymcsg** [comment]
You can the usage of it in demo.
The readme contains some simple usage of the library.

**Comment by altairmizuchi** [comment]
It has been a year already. README still contains nothing about this usage and wiki page is totally outdated. Can you fix it, please?

**Comment by vajiralasantha** [comment]
Anybody found how to use this? I'm totally stucked with updating an old project to a newer version. Wasted a day already :/
