### ISSUE TITLE
Using this lib with CardView: Background color problem

### ISSUE THREAD

**Issue by Rainer-Lang** [cymcsg/UltimateRecyclerView#11]
I'm using this lib with CardView - and I can't set the background color of the view. 
Not the background of the cards!

**Comment by cymcsg** [comment]
Could you show more of your code about the problem?

**Comment by Rainer-Lang** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    android:layout_height="match_parent"
    android:layout_width="match_parent"
    android:background="@color/grey_dedede">

    <com.marshalchen.ultimaterecyclerview.UltimateRecyclerView
        android:id="@+id/rvCardRecyclerView"
        android:layout_height="match_parent"
        android:layout_width="match_parent"
        app:recyclerviewClipToPadding="true"
        app:recyclerviewPadding="2dp"
        app:recyclerviewEmptyView="@layout/empty_view">
    </com.marshalchen.ultimaterecyclerview.UltimateRecyclerView>
...

**Comment by Rainer-Lang** [comment]
Do you need anything else?

**Comment by cymcsg** [comment]
It's a good idea to show more of your code especially the code about adapter.
I do not know how you use the CardView.

**Comment by Rainer-Lang** [comment]
Nothing special. 
I switched from normal RecyclerView with CardView (all was working!) to UltimateRecyclerView.
And then my background color was gone...

**Comment by Rainer-Lang** [comment]
fixed - thanks.

**Comment by CodingHornet** [comment]
@Rainer-Lang Hi,
How did you fixed ?

**Comment by Rainer-Lang** [comment]
@CodingHornet I sitched to the really awesome FastAdapter of @mikepenz 
Have a look. 
@mikepenz has great other libs too, like MaterialDrawer or AboutLibraries or Android-Iconics ....
