### ISSUE TITLE
Back View seeing through front view for SwipeableUltimateRecyclerView

### ISSUE THREAD

**Issue by aprofromindia** [cymcsg/UltimateRecyclerView#113]
My red back view is showing through the front view for SwipeableRecyclerView.... not sure what I am doing wrong?

![screen shot 2015-07-08 at 12 25 16](https://cloud.githubusercontent.com/assets/1256673/8568265/8655e2c8-256c-11e5-999d-ae3c5e219eb8.png)

**Comment by cymcsg** [comment]
Could you tell me what version do you use? The latest version  of UltimateRecyclerview has changed the swiped method.

**Comment by aprofromindia** [comment]
@cymcsg - thanks for the info; we were using 0.3.7. Actually we figured out the problem being the front view's image was being transparent png. sorry for the inconvenience.
