### ISSUE TITLE
Dismiss load more view manually

### ISSUE THREAD

**Issue by zuoshu** [cymcsg/UltimateRecyclerView#114]
Is there any function in UltimateRecyclerView can dismiss loading progress bar?
I wanna give stop loading more if there is no more data.
Thanks in advance.

**Comment by cymcsg** [comment]
You can use ``setCustomLoadMoreView`` to modify the progress bar.

**Comment by zuoshu** [comment]
哦，原来作者是国人，就直接写中文啦。
我是想说，在load more的时候，发现没有更多数据了，有没有接口可以把load more的进度条藏起来。
看了下代码，貌似没有在代码里面show,hide那个进度条的接口

**Comment by cymcsg** [comment]
I think I understand your meaning.As I said above, you can use ``setCustomLoadMoreView`` to set am empty view to hide the loading more progress bar.It is some kind ugly,but it's useful if you need it now.

**Comment by lichenyang1993** [comment]
可以直接把loadmore的visibility设为gone，然后合适的时候（比如下拉刷新的时候）再次显示出来@zuoshu

**Comment by reancool** [comment]
loadmoare   visibility.GONG  has  bug,if do that, progress and text is GONE ,but footerview become white ,the better ..is
when data load finished,you can use 

mAdapter.notifyItemRemoved(mAdapter.getItemCount()-1);
ultimateRecyclerView.disableLoadmore();

if(datalist.isEmpty){
mAdapter.notifyItemRemoved(mAdapter.getItemCount()-1);
ultimateRecyclerView.disableLoadmore();
}

-1 is footerview's  position

the loaderingView is   totally  GONE

**Comment by lowfiend** [comment]
@cymcsg  not working to dismiss load more view
I use  
adapter.setCustomLoadMoreView(LayoutInflater.from(getActivity()) .inflate(R.layout.empty_progressbar, null));
