### ISSUE TITLE
能提示下加载更多时的ui效果是在那里处理的么，只看到有监听，谢了

### ISSUE THREAD

**Issue by huxq17** [cymcsg/UltimateRecyclerView#116]

**Comment by huxq17** [comment]
我仔细读了代码，没有发现有处理加载更多时ui效果的地方，我猜应该是recyclerview自动做出了这种效果。

**Comment by cymcsg** [comment]
Do you want to use a custom loading more view? You can simply use ``setCustomLoadMoreView``.

**Comment by huxq17** [comment]
这个我知道，如果我想控制loadmoreview显示的时间，目前有办法么？

**Comment by huxq17** [comment]
或者我想加个插值器，自定义loadmoreview消失时的动画。

**Comment by cymcsg** [comment]
You can set an empty view when you do not need the loading state any more.

**Comment by huxq17** [comment]
谢了
