### ISSUE TITLE
Bug in 0.3.10 - empty view shown though adapter count 10

### ISSUE THREAD

**Issue by Rainer-Lang** [cymcsg/UltimateRecyclerView#117]
This is only in 0.3.10!
0.3.7 - adapter count 10 => no empty view is shown => correct
0.3.10 - adapter count 10 => empty view is shown => incorrect

**Comment by cymcsg** [comment]
Thank you very much for reporting this.
Could you show more code about this bug?As I can hardly see this in demo.

**Comment by Rainer-Lang** [comment]
The empty view is set in the xml like in your demo - and it's the same layout file as in your demo.
Sorry can't provide much code, but this is the workflow:
1) start activity (viewpager)
2) start fragment
3) load items from db in onActivityCreated() and set in adapter (10 items)
Code in fragment
```java
private void displayData(List<Item> items) {
  m_Adapter.swapElements(items);
}
```
here adapter
```java
public void swapElements(List<Item> items) {
  m_Items = items;
  notifyDataSetChanged();
}
```
Sorry more code is not possible - BUT I will do every test to help to find this bug.

**Comment by Rainer-Lang** [comment]
If I should test something - please let me know?

**Comment by freemiumdev** [comment]
I've the same problem..

**Comment by cymcsg** [comment]
@Rainer-Lang Sorry for that.What kinds of method do you use when the problem occurs?You add or delete some items before the count of the adapter comes to 10.

@freemiumdev Could you show more details about how to let the problem occurs?

**Comment by Rainer-Lang** [comment]
@cymcsg First start of fragment adapter is empty. Then in onActivityCreated I load items from database -> then use displayData()

**Comment by cymcsg** [comment]
@Rainer-Lang  Do you use ``showEmptyView`` or  the empty layout in xml?

**Comment by freemiumdev** [comment]
@cymcsg  In the costructor of adapter  i have   this.events = new ArrayList<Evento>();
later when i loaded data from web service i write this method to display data: 

 public void setList(ArrayList<Evento> list) {
        this.events=list;
        notifyDataSetChanged();
    }

after call this method, the data is displayed, but the emptyview not disappears

**Comment by Rainer-Lang** [comment]
I use emptyview in xml.

**Comment by cymcsg** [comment]
Thank you for reporting this.
I have fixed the problem in the latest version on dev branch.And it'll publish as 0.3.11 soon.
