### ISSUE TITLE
superslim's proguard problem

### ISSUE THREAD

**Issue by Swisyn** [cymcsg/UltimateRecyclerView#12]
I've updated the lib for the latest version and it gives error from proguard;

Warning:com.tonicartos.superslim.LayoutModifierHelper: can't find referenced class com.tonicartos.superslim.Recycler
Warning:there were 4 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)

is it a problem or should i add the superslim library with -dontwarn ?

**Comment by cymcsg** [comment]
I do not think it is a problem.I think you can keep the superslim class to fix the problem.
Or you can ask on https://github.com/TonicArtos/SuperSLiM .
Thank you.
