### ISSUE TITLE
当把linearLayoutManager换成GridLayoutManager就会出现问题

### ISSUE THREAD

**Issue by huxq17** [cymcsg/UltimateRecyclerView#125]
footerview就会出现问题，我看代码发现，footerview只是被加入了recyclerview中，不过不是linearlayoutmanager，那么最后一个item的位置就有可能不在最下面了

**Comment by cymcsg** [comment]
In current version,the loading more view only support LinearLayout.I'll try to find a way to fix it.

**Comment by huxq17** [comment]
我在想还不如把上拉加载更多的操作拿出来，不依赖于recyclerview，这样就不会局限于Linearlayoutmanager了。这只是我的看法，如果解决了，@我下，谢了

**Comment by huxq17** [comment]
我在想还不如把上拉加载更多的操作拿出来，不依赖于recyclerview，这样就不会局限于Linearlayoutmanager了。这只是我的看法，如果解决了，@我下，谢了

**Comment by ljnalex** [comment]
only support LinearLayout??? OMG

**Comment by cymcsg** [comment]
Some features only support Linearlayoutmanager in current version

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue. @ijnaiex @huxq17
