### ISSUE TITLE
mDecor view add one more line on the very bottom

### ISSUE THREAD

**Issue by jjhesk** [cymcsg/UltimateRecyclerView#128]
How do we make it happen when we have added divider line between each item in the linear recycler view. I would like to add one more line on the very bottom and the very beginning.

**Comment by jjhesk** [comment]
resolved! 

here is the code for the solution from using ```showLastDivider```

```java

final HorizontalDividerItemDecoration decor = new HorizontalDividerItemDecoration.Builder(getActivity()).paint(...).

showLastDivider()

.build();

```

**Comment by guobuping** [comment]
That's awesome!
