### ISSUE TITLE
feature enhancement for quick adapter

### ISSUE THREAD

**Issue by jjhesk** [cymcsg/UltimateRecyclerView#135]
check out this adapter, it will give an even better view of the structure from the implementation.
@cymcsg tell me what u think and if it is possible implement it. [awesome implementation](https://github.com/hongyangAndroid/base-adapter-helper)

**Comment by cymcsg** [comment]
I think some feature of the adapter is really helpful.I'll try to find which is the best way to implement it.

**Comment by jjhesk** [comment]
thats a good idea.

**Comment by jjhesk** [comment]
@cymcsg  lets add this on the 0.4 milestone

**Comment by jjhesk** [comment]
there is still outstanding instability issue from the abmob list view and its recycled items during the process. we will need to test it with the real issue first.

**Comment by jjhesk** [comment]
@cymcsg mentioned from the [google group](https://code.google.com/p/android/issues/detail?id=172416) the issue could be related to "the same method name confused" the recyclerview to run. Could it be the [onCreateViewHolder] (https://github.com/cymcsg/UltimateRecyclerView/blob/dev/UltimateRecyclerView/ultimaterecyclerview/src/main/java/com/marshalchen/ultimaterecyclerview/AdmobAdapter.java#L130) that is being confusing??

**Comment by jjhesk** [comment]
I have discovered that the crash is related to the animation. When the items are scrolled too fast and some of the recycled items were not yet to be prepared it initiated the crash.

**Comment by jjhesk** [comment]
looks like this is gonna be helpful [source](https://gist.github.com/darnmason/7bbf8beae24fe7296c8a)

**Comment by cymcsg** [comment]
Does this problem occur when items are scrolled too fast and used animation at the same time?I'm not quite sure about this problem.Let's try to find a way to fix it.

**Comment by jjhesk** [comment]
As from the discussion online, this bug is pointed to the google library bug that need to be fixed by their own. We are now looking forward to the new support library recycler view that comes with the patch to fix these issues. V23.2.1 will works. #342
