### ISSUE TITLE
Multi selection possible?

### ISSUE THREAD

**Issue by Rainer-Lang** [cymcsg/UltimateRecyclerView#137]
Is multi selection possible?
Like here: https://github.com/davideas/FlexibleAdapter

**Comment by cymcsg** [comment]
You can use it but it will lose some features which UltimateAdapter has.

**Comment by Rainer-Lang** [comment]
I want both if possible. ;-)

**Comment by Rainer-Lang** [comment]
You know I really love ultimaterecyclerview but i also need multi selection.

**Comment by jjhesk** [comment]
about just create a new adapter to extend from the URV that will replace the existing feature from the parent. I think it is okay to do so because I have also done that via the expandable adapter and it works like a charm.

**Comment by Rainer-Lang** [comment]
@jjhesk Expandable is also something really useful! :)

**Comment by Rainer-Lang** [comment]
@jjhesk Is it possible to use URVAdapter with expandable and multi selection adapter?

**Comment by jjhesk** [comment]
@Rainer-Lang im looking into [flex](https://github.com/davideas/FlexibleAdapter/blob/master/flexibleAdapter/src/main/java/eu/davidea/common/SelectableAdapter.java)

**Comment by Rainer-Lang** [comment]
@jjhesk This is also my favorite :-)

**Comment by Rainer-Lang** [comment]
@jjhesk Any news about integrating FlexibleAdapter/SelectableAdapter?

**Comment by jjhesk** [comment]
@Rainer-Lang we will come back on 0.5.5 for this feature as we are now working on v23.2.1
