### ISSUE TITLE
Loading view.

### ISSUE THREAD

**Issue by Wolftein** [cymcsg/UltimateRecyclerView#14]
Would you consider adding "Loading" state into the RecyclerView?, empty view will trigger when there isn't any item and loading will trigger the first time the recycler view is retrieving the items.

**Comment by cymcsg** [comment]
Thank you for your good advice!
I'll add this in next version.

**Comment by gouravd** [comment]
Could you also please add an ErrorView too? Currently we are using https://github.com/MeetMe/Android-MultiStateView for handling, loading, empty and erros states

**Comment by cymcsg** [comment]
Now there is a loading state which can be used as loading or error view.
