### ISSUE TITLE
FastScroller mode?

### ISSUE THREAD

**Issue by Swisyn** [cymcsg/UltimateRecyclerView#141]
Hey, could you add fastscroller option to the lib? Maybe you can use this. https://github.com/danoz73/RecyclerViewFastScroller

**Comment by cymcsg** [comment]
Thank you for the advise.
As the library use a view in the recyclerview,I can hardly use it directly.But I'll try to add this feature into the library.

**Comment by Swisyn** [comment]
The library is getting more great than before with the new features. Thanks for your greak work @cymcsg

**Comment by Rainer-Lang** [comment]
Maybe also here: https://github.com/krimin-killr21/MaterialScrollBar

**Comment by jjhesk** [comment]
@Rainer-Lang 
@Swisyn 
i will work on it soon after this loadmore issue is resolved.
