### ISSUE TITLE
Adding empty space below last item

### ISSUE THREAD

**Issue by Noezis** [cymcsg/UltimateRecyclerView#149]
hi,

I enabled load more feature in my recycler view and  I'd like to add empty space below last item so I can show circular animation. I tried:

    <com.marshalchen.ultimaterecyclerview.UltimateRecyclerView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/ultimate_recycler_view"
        android:paddingBottom="50dp"
        android:clipToPadding="false"
        android:scrollbarStyle="outsideOverlay"
        >

but my view is clipped. I just want to add it below last item. I consider adding special item view with preloader anim when load more event is triggered and remove it later, but it's a little bit hacky.

**Comment by cymcsg** [comment]
In current version,it's hard to add empty space ONLY below last item.You can custom your last item in viewholder to achieve this.

**Comment by zeleven** [comment]
@cymcsg I think that is was a bug in the library, because the `clipToPadding` attribute work in the official `RecyclerView`, but it doesn't work in this library.
