### ISSUE TITLE
change color Swipe Refresh

### ISSUE THREAD

**Issue by choiruru** [cymcsg/UltimateRecyclerView#15]
Ho to change color in default swiperefresh (google refresh)? I can't find a method that can to change it.

Thanks **cymcsg**

**Comment by cymcsg** [comment]
Sorry for that.
I'll add a method to set swipe to refresh color soon.
Thank you for reporting that.

**Comment by cymcsg** [comment]
In the latest URV in dev branch,it has both code way and xml way to set default colors.

**Comment by choiruru** [comment]
Okay cymcsg, thanks for it

**Comment by cyberrob** [comment]
I set the color but it still show default color. Is there anything wrong?
````
mRecyclerView.setDefaultSwipeToRefreshColorScheme(
                R.color.refresh_color_1,
                R.color.refresh_color_2,
                R.color.refresh_color_3,
                R.color.refresh_color_4
        );
````
