### ISSUE TITLE
Load More 相关问题

### ISSUE THREAD

**Issue by liuxue0905** [cymcsg/UltimateRecyclerView#150]
1.load more只有在数据数量改变之后才能够再次监听到onLoadMore，那么加载网络数据失败了，无法再继续监听
2.Adapter第一次不设置数据，而是使用empty List，或者null（Adapter中需要判断null时getAdapterCount()方法return 0），那么load more只要enableLoadMore就会回调onLoadMore，根本没有滚动到列表末尾

**Comment by liuxue0905** [comment]
3.setOnLoadMoreListener第一次设置有效值，第二次马上设置null，报空指针啊

**Comment by jjhesk** [comment]
try to make a try catch case @liuxue0905
