### ISSUE TITLE
Error:(1) Attribute "size" has already been defined  (Android Studio) (build tools 22.0.1)

### ISSUE THREAD

**Issue by secApps** [cymcsg/UltimateRecyclerView#151]
I am trying to use this library, but everytime i try to build project it shows Error:(1) Attribute "size" has already been defined. 
This is my app dependencies>>
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.android.support:support-v4:22.2.0'
    compile 'com.android.support:recyclerview-v7:22.2.0'
    compile 'com.github.shell-software:fab:1.1.2'
    compile 'com.android.support:design:22.2.0'
    compile 'com.android.support:cardview-v7:22.2.0'
    compile 'com.android.support:support-v13:22.2.0'
    compile 'com.astuetz:pagerslidingtabstrip:1.0.1'
    compile 'com.github.bumptech.glide:glide:3.6.0'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.0'
    compile project(':recorder')
    compile 'com.marshalchen.ultimaterecyclerview:library:0.3.11'
}

**Comment by amitmiran** [comment]
I'm having similar error: Error:(2) Attribute "icon" has already been defined
Error:(2) Attribute "buttonStyle" has already been defined


build tools ( 'com.android.support:support-v13:22.1.1)

**Comment by cymcsg** [comment]
Fixed in the latest version 0.3.16
