### ISSUE TITLE
scrolling issue

### ISSUE THREAD

**Issue by jjhesk** [cymcsg/UltimateRecyclerView#154]
can anyone help me to think of this issue? @cymcsg @SevanJoe 
When the URV is empty with the request is made and fetch the data into the listview immediately there is no scrolling to the bottom. When the URV is empty with the request is started and fetch the data into the listview with t>0 of the time the listview will scroll to the bottom where the last item is fetched.

**Comment by cymcsg** [comment]
Do you mean if an empty URV loads data for sometime the recyclerview will scroll to the bottom while if URV  loads without delay time it will not scroll?

**Comment by jjhesk** [comment]
@cymcsg loading data from by insert (always scroll to the bottom) VS having a  List<T> items at the beginning (always stay scroll on the top).

**Comment by Rainer-Lang** [comment]
But I have a situation there I need the scrolling after insert.

**Comment by jjhesk** [comment]
do u have the testing code to display?

**Comment by jjhesk** [comment]
```java

   /**
     * example 1 implementation of the switch view
     */
    private BiAdAdapterSwitcher imple_switch_view(final UltimateRecyclerView rv) {
        final adap adp1 = new adap(createadmob(), false, 10, new ArrayList<String>(),
                new AdmobAdapter.AdviewListener() {
                    @Override
                    public RelativeLayout onGenerateAdview() {
                        return createadmob();
                    }
                });
        final regular adp2 = new regular(new ArrayList<String>());
        final BiAdAdapterSwitcher switchable = new BiAdAdapterSwitcher(rv, adp2, adp1);
        return switchable;
    }

```
this is the code part to show there is nothing at beginning.
