### ISSUE TITLE
A line at bottom

### ISSUE THREAD

**Issue by zuoshu** [cymcsg/UltimateRecyclerView#155]
![333](https://cloud.githubusercontent.com/assets/1215475/9287844/72355666-435d-11e5-998b-f1c10a0ffb70.png)

why there is  a line below the list, and how to remove it

**Comment by cymcsg** [comment]
I have seen that the last item is an empty item.Could you remove that item?

**Comment by zuoshu** [comment]
There should be only 2 items data in the list, and I did not add any items to the bottom.

**Comment by zuoshu** [comment]
the xml is like this

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <FrameLayout
        android:id="@+id/content"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.marshalchen.ultimaterecyclerview.UltimateRecyclerView
            android:id="@+id/ultimate_recycler_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </FrameLayout>
</LinearLayout>

**Comment by zuoshu** [comment]
It's the customLoadMoreView, disableLoadmore() if there is no more data works for me.
THX

**Comment by cymcsg** [comment]
I tried in demo that if I use customLoadMoreView and use disableLoadmore at the same time and there is no redundant item. Could you change some code in demo to make the demo like your program and find out  the reason of the problem?

**Comment by zuoshu** [comment]
the reason is I missed disableLoadMore() if there is no more data.
add disableLoadMore should fix.
my final code look like this
![image](https://cloud.githubusercontent.com/assets/1215475/9518621/9d65fafc-4cea-11e5-8c17-e9a21d9f8fce.png)
