### ISSUE TITLE
UltimateRecyclerView's background

### ISSUE THREAD

**Issue by Swisyn** [cymcsg/UltimateRecyclerView#16]
Could you remove the background color or recyclerview (ultimate_recycler_view_layout.xml,   android:background="#ffffff" ) and make it optional with styles or something?

Because it doesn't seem good with white background. 

Also another suggestion is could you add some attributes to VerticalSwipeRefreshLayout for changing refreshing colors? like; app:recyclerviewRefreshingColors="@color\refreshing_colors" which uses array of 4 colors.

Thank you so much again @cymcsg

**Comment by cymcsg** [comment]
Thank you for giving such useful advices.
I'll add a method to set background color of recyclerview and the default background color will be removed.

For the second suggestion,I'll add both code style and xml style to define the swipe refresh color soon.

**Comment by cymcsg** [comment]
I have added a method to set background color of recyclerview.
In the latest URV in dev branch,it has both code way and xml way to set default colors.

**Comment by Swisyn** [comment]
Thank you so much for your effort. How can i sync my project with the dev branch's gradle? I couldn't see any gradle compilation text or something...

**Comment by cymcsg** [comment]
If you use the project source code in your project,you can simply check out the dev branch.Or if you want to use the released version, you would wait for sometime.I will released the version in tomorrow or the day after tomorrow.

**Comment by cymcsg** [comment]
Now you can use version 0.3.2 to fix the problem

**Comment by Swisyn** [comment]
@cymcsg thank you so much
