### ISSUE TITLE
fab_colorNormal / fab_colorPressed / fab_size

### ISSUE THREAD

**Issue by Rainer-Lang** [cymcsg/UltimateRecyclerView#161]
I get an error with "0.3.16" (not with 0.3.14)
```fab_colorNormal``` ```fab_colorPressed``` ```fab_size```
has already been defined.

Is it possible to prefix all with "urv_" to avoid problems in future?

**Comment by cymcsg** [comment]
Sorry for that.I have used a wrong name.I'll try to fix it soon.

**Comment by Rainer-Lang** [comment]
Nevermind. Thanks.

**Comment by jjhesk** [comment]
please leave the note for the new version release. Just to avoid future queries when this configuration has changed.

**Comment by moisesvs** [comment]
When will this error be fix in release version?

**Comment by cymcsg** [comment]
The version 0.3.17 has changed attr name from  from ``fab_**`` to ``urv_fab_**`` .The version has been released yesterday.
