### ISSUE TITLE
setEmptyView issue

### ISSUE THREAD

**Issue by Swisyn** [cymcsg/UltimateRecyclerView#166]
when i try to change empty_view of recyclerview which is set in xml, it gives that error;

  java.lang.IllegalStateException: ViewStub must have a non-null ViewGroup viewParent
            at android.view.ViewStub.inflate(ViewStub.java:292)
            at com.marshalchen.ultimaterecyclerview.UltimateRecyclerView.setEmptyView(UltimateRecyclerView.java:183)

in both codes;
 getUltimateRecyclerView().setEmptyView(getResources().getIdentifier("empty_favorites","layout",getActivity().getPackageName()));
    getUltimateRecyclerView().setEmptyView(R.layout.empty_favorites);

is there way to change empty_view dynamically?

**Comment by cymcsg** [comment]
As ViewStub can only inflate once, it's hard to change empty_view dynamically unless change ViewStub to View.
