### ISSUE TITLE
Please change so that RecylerView is not permanently white.

### ISSUE THREAD

**Issue by jofor** [cymcsg/UltimateRecyclerView#17]
<android.support.v7.widget.RecyclerView
            android:id="@+id/ultimate_list"
            android:background="#ffffff"
            android:layout_width="match_parent"
            android:layout_height="match_parent"></android.support.v7.widget.RecyclerView>

This part of the code. I am not able to override it in gradle. Please remove the #ffffff I do not want my recyclerview to be white at all times.

**Comment by cymcsg** [comment]
In the latest version of UltimateRecyclerview in dev branch the background has been already removed and add a new method to set the background.If you want to use it immediately you can check it out now.The version will be released in jcenter soon.
You can also read the issue [here](https://github.com/cymcsg/UltimateRecyclerView/issues/16)

**Comment by cymcsg** [comment]
Now you can use version 0.3.2 to fix the problem

**Comment by jofor** [comment]
Sweet!
