### ISSUE TITLE
SetEmptyView crash

### ISSUE THREAD

**Issue by KingWu** [cymcsg/UltimateRecyclerView#170]
Try to implement NestFragment structure.

The View Strucuture

Fragment
|--> View Pager
       |--> Child Fragment
               |-> Recycle List 

SetEmptyView on child fragment will get this error.

java.lang.IllegalStateException: ViewStub must have a non-null ViewGroup viewParent
            at android.view.ViewStub.inflate(ViewStub.java:292)

**Comment by cymcsg** [comment]
Could you show some code about this problem?

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.
