### ISSUE TITLE
Is an undo-snackbar functionality provided like in eg FlexibleAdapter?

### ISSUE THREAD

**Issue by Rainer-Lang** [cymcsg/UltimateRecyclerView#171]

**Comment by cymcsg** [comment]
Could you show more about this feature? Where is the ``FlexibleAdapter`` in eg?

**Comment by Rainer-Lang** [comment]
Please look here: https://github.com/davideas/FlexibleAdapter

**Comment by Rainer-Lang** [comment]
FlexibleAdapter has also a search funtionality in the dev-branch (I haven't tried it yet).
