### ISSUE TITLE
Problem with library PermissionsDispatcher with plugin android-apt

### ISSUE THREAD

**Issue by moisesvs** [cymcsg/UltimateRecyclerView#178]
Hi! 

I want integrate the library permissionDispatcher with ultimateRecyclerView but when I included this library in my file gradle.build the UltimateRecyclerView doesn't work the listener onUpOrCancelMotionEvent and setDefaultOnRefreshListener. Could you try add this library?

Regards

**Comment by cymcsg** [comment]
What do you mean by  ``permissionDispatcher` `library?

**Comment by moisesvs** [comment]
This library:
http://hotchemi.github.io/PermissionsDispatcher/

**Comment by moisesvs** [comment]
And the library Android-APT is this:
https://bitbucket.org/hvisser/android-apt

**Comment by moisesvs** [comment]
Any ideas? Could integrate this library together with UltimateRecyclerView? Thanks.

**Comment by cymcsg** [comment]
With the Readme in that library,I think it can be integrated with UltimateRecyclerview.But I do not read the source code of that library so I do not know how it achieves.Maybe these two libraries override something at the same time.

**Comment by moisesvs** [comment]
But if that library override something at the same time will get error the gradle builder, no?. I don't know that is happening but you can read the source code un the github page, no?.

This library is useful to detect the app permissions in Android 6.0 (Android m)

Do you think that in the future could fix?

**Comment by cymcsg** [comment]
It's only my guess and they are methods not attrs. 
I do not think it is a main feature in URV but it's good idea to be compatible with URV.
