### ISSUE TITLE
关于加载更多和multiviewtype

### ISSUE THREAD

**Issue by buaacloud** [cymcsg/UltimateRecyclerView#181]
感谢此library大大简化了开发，使用中有些问题想请教：
1、加载更多的使用体验不太好，使用前必须enableLoadmore(),要让loading的view消失需要disableLoadmore，我测试时候还得刷新adapter才有效果。自定义的loading view也不能保留布局参数，在用的时候加了个progressbar，本来想放在底部中间位置，可一直在左边，最后这样解决，recyclerVeiw.setCustomLoadMoreView(LayoutInflater.from(this)
        .inflate(R.layout.recycler_custom_bottom_progressbar, recyclerVeiw. false));默认的加载view是否要这种方式。总的来说，这种方式不能很好的满足的一种场景：loadMore里我首先需要判断网络，没有网络我就直接return了，或者没有更多数据了，我只能disable ,然后我在enable,还有重新设置loading view .觉得下拉刷新的模式就可以很好的满足需求。直接设置监听就是了，停止刷新一个设置一个标志就是了。
2、现在的multiviewtype支持就不能加载更多了？

可能我没有很好的理解用法，希望能给些指点！

**Comment by cymcsg** [comment]
The loading more view is a item in the adapter so it can hardly use as swipe to refresh.But I'll try to make it more easy to use.

**Comment by buaacloud** [comment]
Thanks for your reply, looking forward to your update!
