### ISSUE TITLE
Bug (?) : choosing "MultiViewType" in the sample has weird views, like empty-view even though there is data shown

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [cymcsg/UltimateRecyclerView#184]
Just look at this:

![device-2015-09-09-095212](https://cloud.githubusercontent.com/assets/5357526/9755165/7be9f444-56d8-11e5-9f49-e0053152ee69.png)

It shows  "no data here" in the middle, and it has action bar items that don't do anything, plus it has something on the top-left that doesn't do anything.

**Comment by cymcsg** [comment]
``The action bar items that don't do anything, plus it has something on the top-left that doesn't do anything.`` 
The items on the actionbar do not have any other special features so the demo do not achieve them in this activity.

**Comment by AndroidDeveloperLB** [comment]
Why add them then?
And why did you close this issue? Don't you see the "no data here" text?

**Comment by cymcsg** [comment]
You can add them like in the MainActivity.
Do you also need empty view in multitype?

**Comment by AndroidDeveloperLB** [comment]
I don't understand. I run the sample, and I see the "no data here" text, even though there are items.
Don't you see it's a bug?
Why show that there are no items, when there clearly are items shown?
