### ISSUE TITLE
Bug: choosing "Load More Test" , and then playing with the sample, allow showing empty space at the top

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [cymcsg/UltimateRecyclerView#185]
I've chosen  "Load More Test", and then I played with it for a while: scrolling and swiping a lot.
Then I got to this weird situation:

![device-2015-09-09-095632](https://cloud.githubusercontent.com/assets/5357526/9755244/137f24dc-56d9-11e5-9ee4-4ccc72434d0c.png)

**Comment by AndroidDeveloperLB** [comment]
Same happens on the first sample, actually. I just play with it for a while, and it can occur:

![device-2015-09-09-095833](https://cloud.githubusercontent.com/assets/5357526/9755279/5bd4188c-56d9-11e5-9fa3-ff934fbe670c.png)

**Comment by yuanjunli** [comment]
i met the problem too when i use the parallaxHeader

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue. @AndroidDeveloperLB @yuanjunli

**Comment by AndroidDeveloperLB** [comment]
@jjhesk I don't understand. Did you fix this issue?
