### ISSUE TITLE
Sticky header with multi view adapter

### ISSUE THREAD

**Issue by alirezaaa** [cymcsg/UltimateRecyclerView#187]
Hi,

First of all, I must thank you for this great library which helped me a lot.
I implemented the sticky header but it will be shown for two layouts used with the recycler. I need to show the sticky header only for one of layouts.

Thanks.

**Comment by cymcsg** [comment]
Do you need a different way as demo shows?I do not quite understand ``one layouts`` means

**Comment by alirezaaa** [comment]
@cymcsg I'm using `UltimateDifferentViewTypeAdapter`, I declared two layouts. The sticky header is showing for the two layouts by default. but I want to show the sticky header only for the first layout.
Yes, I need a different way as demo shows.

**Comment by Kaushik1502** [comment]
@cymcsg how can I use this library without header for item.  Means I want to omit onCreateHeaderViewHolder and onBindHeaderViewHolder.

Thanks

**Comment by Studentessa** [comment]
hi @meNESS did you get to do what yo wanted? I also want a sticky header and multipleviewsadapter, but I can't have both, only one of the options.

thanks

**Comment by meNESS** [comment]
@Studentessa Use [FastAdapter](https://github.com/mikepenz/FastAdapter) instead of `UltimateRecyclerView`.
