### ISSUE TITLE
Loading indicator freeze

### ISSUE THREAD

**Issue by zxy198717** [cymcsg/UltimateRecyclerView#191]
![screenshot_2015-09-16-10-42-22](https://cloud.githubusercontent.com/assets/785333/9896411/3b9fbcde-5c6e-11e5-811e-edc66e5478e2.png)

Pull again and again. 
Used android support library v23.0.0, please help to check.

**Comment by jjhesk** [comment]
i have no idea how it happened. I guess we can try on lower the api level to v22.

**Comment by jjhesk** [comment]
this library is currently not yet using API23.0.0. to compile however it is safe to compile that in your project with API 23.0.0
