### ISSUE TITLE
Method .setRefreshing(true) is not working when init UltimateRecyclerView

### ISSUE THREAD

**Issue by DenisMondon** [cymcsg/UltimateRecyclerView#192]
Hi,

When the UltimateRecyclerView is initialized in onCreateView, I write this:
```java
mListView = (UltimateRecyclerView) view.findViewById(R.id.fragment_list_view_pageable_list);
mListView.setRefreshing(true);
AsyncTask.execute...
```
But the SwipeRefreshLayout is not displayed.
How can I show it during the asynctask?

Thanks.
Denis

**Comment by kientux** [comment]
This is a bug of Android `SwipeRefreshLayout`. `UltimateRecyclerView` only call `setRefreshing(boolean)` method of `SwipeRefreshLayout`.

If you need to show indicator initially, you must use this:

```java
ultimateRecyclerView.post(new Runnable() {
    @Override
    public void run() {
        ultimateRecyclerView.setRefreshing(true);
    }
    });
```

**Comment by DenisMondon** [comment]
Thank you! It works perfectly!
