### ISSUE TITLE
UltimateDifferentViewTypeAdapter with HeaderView

### ISSUE THREAD

**Issue by TedaLIEz** [cymcsg/UltimateRecyclerView#197]
I write a adapter class which extends UltimateDifferentViewTypeAdapter and I implements the method onBindHeaderViewHolder and onCreateHeaderViewHolder.But only to find that the first item is attached to the headerview while others doesn't.
How do I attach headerview to every item as UltimateViewAdapter does ?

thx to your works.

**Comment by Yellu** [comment]
Hi, in my case header not visible, please anyone help me, I am stuck here.
