### ISSUE TITLE
DiableLoadMore() effect to Parallax Header!

### ISSUE THREAD

**Issue by hungnguyenvan** [cymcsg/UltimateRecyclerView#198]
Hi all! Please help me!
When i use Load more function, i disable LoadMore layout when finish loading. after that, i reenable LoadMore function of UltimateRecyclerView, so it make  the positon of Parralax Header is lower.
This is code :    
![device-2015-09-25-105937](https://cloud.githubusercontent.com/assets/1708448/10092807/8cd265ae-6374-11e5-8adc-1981c804c604.png)

ultimateRecyclerView.setOnLoadMoreListener(new UltimateRecyclerView.OnLoadMoreListener() {
            @Override
            public void loadMore(int itemsCount, final int maxLastVisiblePosition) {
                Handler handler = new Handler();
                handler.postDelayed(new Runnable() {
                    public void run() {
                        ultimateRecyclerView.disableLoadmore();
                        ultimateRecyclerView.invalidate();
                        linearLayoutManager.scrollToPositionWithOffset(maxLastVisiblePosition, -1);
                    }
                }, 1000);
            }
        });

Many Thanks!

**Comment by jjhesk** [comment]
yes. i have the same thing.. this should be a bug.

**Comment by carlastabile** [comment]
I have the same issue but I don't think is related to the load more, I'm not even using it. I think this happens when we set the parallax header more than one time but don't know how to fix it.

**Comment by jjhesk** [comment]
please now read #276
