### ISSUE TITLE
如何设置刷新圆圈距离顶部的距离？

### ISSUE THREAD

**Issue by love999** [cymcsg/UltimateRecyclerView#21]
我的recyclerview上方有toolbar遮挡了一部分，这样刷新圆圈出现的位置就被toolbar挡住了，我没找到类似setDistanceToTriggerSync (int distance)的方法。

**Comment by cymcsg** [comment]
The demo also use toolbar above the recyclerview.So I wonder what the difference between the demo and your app.

**Comment by love999** [comment]
demo中recyclerview是above toolbar的，我的app中recyclerview是fill_parent的，toolbar在屏幕上方。刷新的圆圈大约距离屏幕上方40～50DP左右，恰好会被我的toolbar遮挡一部分。

**Comment by cymcsg** [comment]
In fact I think you can use the swipe refresh layout in UltimateRecyclerview which contains the ``setDistanceToTriggerSync`` method, and I will add this method in URV directly soon.
But in my opinion,this method is not the solution for your apps if I understand right as the ``setDistanceToTriggerSync`` method  only means ``Set the distance to trigger a sync in dips``.

**Comment by love999** [comment]
确实如此，但swipe refresh layout的api中我也没找到其他方法可以设置刷新的位置了
