### ISSUE TITLE
Custom Loading more view

### ISSUE THREAD

**Issue by alirezaaa** [cymcsg/UltimateRecyclerView#219]
Hi,

I'm trying to set a custom loading more view, but it's layout parameters will be changed by your library! I want to put my loading progress bar at center in its parent but currently I cannot do that. Moreover, the progress bar at the end of my RecyclerView if there is no page anymore, wouldn't be removed. How can I fix these problems?

Thanks.

**Comment by Odaym** [comment]
custom load more view does not work, I've tried absolutely everything, there is no way even if you copy his code. Tried with CustomUltimateRecyclerView and with UltimateRecyclerView, no hope

**Comment by jjhesk** [comment]
i have made some similar design pattern to work with this mechanism and issued in another [library](https://github.com/jjhesk/URVSugarOverlay/blob/master/LayoutCollection/LayoutCollections/src/main/java/com/hkm/layout/fragment/patchHyprbid.java) this is the sample code.

**Comment by Odaym** [comment]
well I'm out, going to go my own way with this, if you notice even with a kind of large number of items his implementation really starts to cause a LOT of visual stutter, that's something really minimal and at least take care of that

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue. @Odaym @alirezaaa
