### ISSUE TITLE
After disable loadmore,the vertical scrollbar can't reach to the bottom

### ISSUE THREAD

**Issue by lichenyang1993** [cymcsg/UltimateRecyclerView#221]
I use the following code to disable loadmore after load all the items,After that,I noticed that ,the vertical scrollbar can't reach to the bottom.What I should do?Thanks!

     mRecycler.disableLoadmore();
     mRecycler.invalidate();
     linearLayoutManager.scrollToPositionWithOffset(maxLastVisiblePosition, -1);

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.
