### ISSUE TITLE
SwipeLayout click listener

### ISSUE THREAD

**Issue by raviteja83** [cymcsg/UltimateRecyclerView#230]
Using swipeAdapter swipelayout ,say delete button,click listener is working but the click listener on the recyclerview row is not working

**Comment by yuanjunli** [comment]
where is you recyclerview row(item) listener ?here is the sample's code and work well for me 
       @Override
    public UltimateRecyclerviewViewHolder onCreateViewHolder(ViewGroup parent) {
        final Context context = parent.getContext();
        View view = LayoutInflater.from(context).inflate(R.layout.item_share_swipeable, parent, false);
        view.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                
            }
        });

**Comment by PsyGik** [comment]
@yuanjunli Do you have state selectors on your list item? Like state_pressed | state_focused etc.?
