### ISSUE TITLE
after setHeader（view） the header did not appear

### ISSUE THREAD

**Issue by ForgetV** [cymcsg/UltimateRecyclerView#231]
questionLv = (UltimateRecyclerView) viewRoot.findViewById(R.id.rv);
        questionLv.setOnLoadMoreListener(new UltimateRecyclerView.OnLoadMoreListener() {
            @Override
            public void loadMore(int itemsCount, int maxLastVisiblePosition) {
            }
        });
        questionLv.setDefaultOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh() {
            }
        });
        questionLv.setLayoutManager(new LinearLayoutManager(mActivity));
        questionLv.enableLoadmore();
        LayoutInflater inflater = LayoutInflater.from(mActivity);
        View convertView = inflater.inflate(R.layout.header, null);
        questionLv.setNormalHeader(convertView);

**Comment by GuyAvraham** [comment]
+1
