### ISSUE TITLE
Pull to refresh while loading more bug

### ISSUE THREAD

**Issue by anupsarode** [cymcsg/UltimateRecyclerView#232]
Data set to be loaded
-----------------------------

- String 1
- String 2
- String 3
- String 4
- String 5
- String 6
- String 7
- String 8
- String 9
- String 10
- String 11

- Recycler view is set with refresh (not custom) and load more listener.
- When initialized first 5 items are loaded from the above data set
- Scoll to bottom to load more. Loadin more takes some time to connect to server and fetch data
- In the meantime, scoll up and pull to refresh to load first 5 items from data set again
- Log shows first 5 items are loaded. But recycler view populates the following data

- String 6
- String 2
- String 3
- String 4
- String 5

The bug is, the first item is always the 6 th item in recycler view even though the REST Response log shows that first 5 items are loaded.

On Refresh, I clear the adapter, clear the ListArray. 

Am I doing something incorrect?

**Comment by cymcsg** [comment]
Do you find it occurs in demo? If the demo also has the bug,it's more convenient for me to find the bug.

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.
