### ISSUE TITLE
how to get current offset position

### ISSUE THREAD

**Issue by agromilo** [cymcsg/UltimateRecyclerView#233]
Can I get current position on list?
scrollVerticallyToPosition is scroll list to selected position, but no way to get ?

getCurrentScrollY - always return 0

**Comment by jjhesk** [comment]
depends on what kind of layout manager you are using. 
In linearlayout manager you can call out the [the function get vertical position](https://github.com/cymcsg/UltimateRecyclerView/blob/master/UltimateRecyclerView/ultimaterecyclerview/src/main/java/com/marshalchen/ultimaterecyclerview/UltimateRecyclerView.java#L1028-L1037) 

```java

    @Override
    public void scrollVerticallyTo(int y) {
        URLogs.d("vertically");
        View firstVisibleChild = getChildAt(0);
        if (firstVisibleChild != null) {
            int baseHeight = firstVisibleChild.getHeight();
            int position = y / baseHeight;
            scrollVerticallyToPosition(position);
        }
    }

    public void scrollVerticallyToPosition(int position) {
        RecyclerView.LayoutManager lm = getLayoutManager();

        if (lm != null && lm instanceof LinearLayoutManager) {
            ((LinearLayoutManager) lm).scrollToPositionWithOffset(position, 0);
        } else {
            lm.scrollToPosition(position);
        }
    }
```

**Comment by jjhesk** [comment]
let me know if it resolved ur issue @agromilo
