### ISSUE TITLE
SimpleItemTouchHelperCallback: setAlpha() crashes on older devices < API11

### ISSUE THREAD

**Issue by cjetrifork** [cymcsg/UltimateRecyclerView#235]
SimpleItemTouchHelperCallback.setAlpha() crashes our app on devices < API11. Please add use of ViewCompat instead or some other solution.

Our specific issue is in clearView() line 110 but it's also used in onChildDraw().

**Comment by cymcsg** [comment]
The current version of the  library do not support on the devices which API <11.
