### ISSUE TITLE
setOverScrollMode() doesn't work

### ISSUE THREAD

**Issue by meNESS** [cymcsg/UltimateRecyclerView#238]
Hi,

```recyclerView.setOverScrollMode(View.OVER_SCROLL_NEVER);``` doesn't work! I want to disable the glow of my recyclerview while scrolling vertically.

**Comment by vivian8725118** [comment]
I have encountered this problem too when using scrollview,and I don't know how to solve it now.I just change the color of the glow so that it doesn't seem so obvious.

**Comment by alirezaaa** [comment]
@vivian8725118 Don't worry. The owner added bug label to this issue, means he know what the problem is. It will be fixed soon I hope :)

**Comment by vivian8725118** [comment]
WOW,that's cool,thanks

发自我的 iPhone

**Comment by jjhesk** [comment]
@vivian8725118 did you try `mRecyclerView.recyclerview` to api this call?
