### ISSUE TITLE
关于loadmore的问题

### ISSUE THREAD

**Issue by 416679828** [cymcsg/UltimateRecyclerView#239]
我在oncreate方法里面执行了一次网络调用,然后在OnLoadMoreListener中分页加载也执行了网络调用,但是我并没有上拉操作,为什么我一打开程序执行了2次网络调用操作代码。分别在oncreate里面执行了一次,
在OnLoadMoreListener中执行了一次。但是我把oncreate里的网络操作注释掉后，OnLoadMoreListener中的网络代码也不执行了......................怎么解决？？？？
第二：调用insert方法插入初始数据,初始界面就默认跳到插入的最后那一项了。怎么解决？因为我是先调用网络接口插入数据的，然后才可能进行loadmore分页操作。

**Comment by yuanjunli** [comment]
检查你第一次在Oncreate方法里边请求网络返回的数据是不是只有几项，在手机屏幕里看到最后一项，如果是，那会继续加载的；

**Comment by jjhesk** [comment]
#276 improved in here.
