### ISSUE TITLE
Strange issue in row visibility

### ISSUE THREAD

**Issue by frodberserk** [cymcsg/UltimateRecyclerView#24]
I am facing a strange behaviour. I have an adapter extending UltimateViewAdapter. It is showing one row less that it must show in actual. If I setView count to 1, it shows no rows.

**Comment by cymcsg** [comment]
Do you use the method ``setParallaxHeader``? If so , you should change some code in your adapter like demo.

**Comment by frodberserk** [comment]
No, I haven't used that method. I just added customLoadMore view.

**Comment by cymcsg** [comment]
Have you tried the latest version of URV?

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue. @frodberserk
