### ISSUE TITLE
GridLayout can't load more in "GridLayoutRVTest"

### ISSUE THREAD

**Issue by Icanmoveyoui** [cymcsg/UltimateRecyclerView#241]
GridLayout can't load more in "GridLayoutRVTest"

**Comment by saran2somu** [comment]
Me also.... Same problem

**Comment by jjhesk** [comment]
it is a bug and l have found the bug location we need to wait @cymcsg to make the update for the new version because i dont have the access right to update the library.

**Comment by cymcsg** [comment]
I am looking forward to your update :)

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.  @Icanmoveyoui @saran2somu
