### ISSUE TITLE
Align Left FloatingActionsMenu

### ISSUE THREAD

**Issue by ayhansalami** [cymcsg/UltimateRecyclerView#242]
I want to align left FloatingActionsMenu and i've been added layout_alignParentLeft to this but still menus on right of screen.
please help me.
sorry for my english:)

**Comment by ayhansalami** [comment]
solution:
fork repository and add it to your project dependency.
edit ultimate_recycler_view_layout.xml and custom_recycler_view_layout.xml files and replace layout_alignParentRith with layout_alignParentLeft

**Comment by jjhesk** [comment]
yep u got it. @ayhansalami
