### ISSUE TITLE
Overlap on Sticky 

### ISSUE THREAD

**Issue by JackED42** [cymcsg/UltimateRecyclerView#245]
I have created a SwipeableUltimateViewAdapter, and have followed the usual steps to create sticky headers. 

When I do this, the header overlaps on the first item below it. I have attached a screenshot, it is quite hard to see where the header view starts, but if you look at the shadow it is easier to see.

![screenshot 25 november 2015 23-39](https://cloud.githubusercontent.com/assets/7283943/11412050/986e9992-93cf-11e5-98a1-7b3f3c681689.jpg)

**Comment by cymcsg** [comment]
Do you mean you want to customize your header of the item?
