### ISSUE TITLE
GridLayout Load More not working 

### ISSUE THREAD

**Issue by saran2somu** [cymcsg/UltimateRecyclerView#247]
Hi , 

 I have implement the UltimateRecyclerView in Fragment and activity as the example , but the load more interface is not fired in end of scroll .

**Comment by cymcsg** [comment]
The load more feature with Gridlayout do not very compatible with current version of URV

**Comment by jjhesk** [comment]
please now read #276

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue. @saran2somu
