### ISSUE TITLE
Custom loadMore view doesn't hide after disableMore()

### ISSUE THREAD

**Issue by itslayo** [cymcsg/UltimateRecyclerView#252]
I'm using latest version of UltimateRecyclerView : 0.3.18
In a sample project it works properly but I don't understand what's wrong with my code

Init:
`

    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.fragment_list, container, false);
        ButterKnife.bind(this, rootView);
        recyclerView.setHasFixedSize(false);
        recyclerView.addItemDividerDecoration(getActivity());
        recyclerView.setEmptyView(R.layout.recyclerview_empty);
        linearLayoutManager = new LinearLayoutManager(getActivity());
        recyclerView.setLayoutManager(linearLayoutManager);
        simpleAdapter = new SimpleAdapter(questions);
        recyclerView.enableLoadmore();
        simpleAdapter.setCustomLoadMoreView(LayoutInflater.from(getActivity())
                .inflate(R.layout.custom_bottom_progressbar, null));
        recyclerView.setAdapter(simpleAdapter);
        recyclerView.setOnLoadMoreListener(new UltimateRecyclerView.OnLoadMoreListener() {
            @Override
            public void loadMore(int itemsCount, int maxLastVisiblePosition) {
                loadDataOffset = itemsCount;
                if (itemsCount < serverItemsCount) {
                    loadDataOffset = itemsCount - 1;
                    loadData(loadDataOffset);
                } else {
                    recyclerView.disableLoadmore();
                    recyclerView.invalidate();
                    linearLayoutManager.scrollToPositionWithOffset(maxLastVisiblePosition, -1);
                }
            }
        });
        initData();
        return rootView;
    }`

Adapter:
`
public class SimpleAdapter extends UltimateViewAdapter<SimpleAdapter.SimpleAdapterViewHolder> {
    private List<QuizQuestion> questions;
    public SimpleAdapter(List<QuizQuestion> questions) {this.questions = questions;}

    @Override
    public void onBindViewHolder(final SimpleAdapterViewHolder holder, int position) {
        if (position < getItemCount() && (customHeaderView != null ? position <= questions.size() : position < questions.size()) && (customHeaderView == null || position > 0)) {
            holder.txtViewTitle.setText(questions.get(customHeaderView != null ? position - 1 : position).getTitle());
            holder.txtViewLevel.setText(questions.get(customHeaderView != null ? position - 1 : position).getLevel());
            SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy HH:mm:SS");
            Date creationDate = new Date(questions.get(customHeaderView != null ? position - 1 : position).getCreationDate());
            holder.txtViewCreationDate.setText(df.format(creationDate));
        }

    }

    @Override
    public int getAdapterItemCount() {
        return questions.size();
    }

    @Override
    public SimpleAdapterViewHolder getViewHolder(View view) {
        return new SimpleAdapterViewHolder(view, false);
    }

    @Override
    public SimpleAdapterViewHolder onCreateViewHolder(ViewGroup parent) {
        View v = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.question_item_list, parent, false);
        SimpleAdapterViewHolder vh = new SimpleAdapterViewHolder(v, true);
        return vh;
    }

    @Override
    public long generateHeaderId(int position) {
        return 0;
    }

    @Override
    public RecyclerView.ViewHolder onCreateHeaderViewHolder(ViewGroup parent) {
        return null;
    }

    @Override
    public void onBindHeaderViewHolder(RecyclerView.ViewHolder holder, int position) {

    }

    public class SimpleAdapterViewHolder extends UltimateRecyclerviewViewHolder {
        TextView txtViewTitle;
        TextView txtViewLevel;
        TextView txtViewCreationDate;

        public  SimpleAdapterViewHolder(View itemView, boolean isItem) {
            super(itemView);
            if (isItem) {
                txtViewTitle = (TextView) itemView.findViewById(R.id.question_list_title);
                txtViewLevel = (TextView) itemView.findViewById(R.id.question_list_level);
                txtViewCreationDate = (TextView) itemView.findViewById(R.id.question_list_creation_date);
            }

        }

        @Override
        public void onItemSelected() {
            itemView.setBackgroundColor(Color.LTGRAY);
        }

        @Override
        public void onItemClear() {
            itemView.setBackgroundColor(0);
        }
    }}`

**Comment by reancool** [comment]
when data load finished,you can use 

mAdapter.notifyItemRemoved(mAdapter.getItemCount()-1);
ultimateRecyclerView.disableLoadmore();

if(datalist.isEmpty){
mAdapter.notifyItemRemoved(mAdapter.getItemCount()-1);
ultimateRecyclerView.disableLoadmore();
}

-1 is footerview's  position

the loaderingView is GONE

**Comment by SwiftyWang** [comment]
@reancool how to reshow the loadmore, the app will crash when I pull to refresh the list.
msg: Called attach on a child which is not detached.

**Comment by reancool** [comment]
@SwiftyWang  actually I give up....UltimateRecyclerView is not suitable for my project。  I found that there are  some problem。Now  I use https://github.com/CymChad/BaseRecyclerViewAdapterHelper。 I THINK IS'T MORE EASIER.....
I also imitate okgo
https://github.com/jeasonlzy/okhttp-OkGo

**Comment by SwiftyWang** [comment]
@reancool finally I find a workaround. please see https://github.com/cymcsg/UltimateRecyclerView/issues/435
I think the repository own has given up this repository.. so sad.
