### ISSUE TITLE
Empty view won't show when adapter item count is zero because using loading more view

### ISSUE THREAD

**Issue by bitjjj** [cymcsg/UltimateRecyclerView#26]
I find your code about showing or hiding empty view as follows:
if (mRecyclerView.getAdapter().getItemCount() == 0 && mEmptyId != 0) {
                        mEmpty.setVisibility(View.VISIBLE);
                    } else if (mEmptyId != 0) {
                        mEmpty.setVisibility(View.GONE);
                    }

There is a bug if you add load more view. You can see mRecyclerView.getAdapter().getItemCount() will never be ==0 because the return result of getItemCount method will be ==1.

Now I have to use the following method to fix this problem:
@Override
    public int getAdapterItemCount() {
        int fixHeaderFooterBug = 0;
        if(mItems.size() == 0 && getCustomLoadMoreView() != null)fixHeaderFooterBug--;
        if(mItems.size() == 0 && getCustomHeaderView() != null)fixHeaderFooterBug--;
        return mItems.size() + fixHeaderFooterBug;
    }

Can you fix this bug ASAP. Thank you very much

**Comment by cymcsg** [comment]
I changed ``mRecyclerView.getAdapter().getItemCount()`` to  ``mAdapter.getAdapterItemCount()`` in the latest version  .The method ``getAdapterItemCount`` is defined in the custom adapter so I think this can fix the problem.
I hope your result with this fix.

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.  @bitjjj
