### ISSUE TITLE
How to set adaptor to ultimateRecyclerView

### ISSUE THREAD

**Issue by amankumarjain** [cymcsg/UltimateRecyclerView#260]
simpleRecyclerViewAdapter = new SimpleAdapter(arrayList); //array List is not allowed in SimpleAdaptor.
ultimateRecyclerView.setAdapter(simpleRecyclerViewAdaptor);

**Comment by amankumarjain** [comment]
Please help me fast i got stuck in between. Thanks in advance.

**Comment by jjhesk** [comment]
you need to extend anything from UltimateViewAdapter
