### ISSUE TITLE
UltimateRecyclerView pull down bug  when app run on android 4.4.x

### ISSUE THREAD

**Issue by alanum** [cymcsg/UltimateRecyclerView#265]
when i run my app on 4.4.x  the pull to refresh work abnormal.  it will stop animation and floating on my page when my finger leaved screen
code as followed:
******
UltimateRecyclerView recyclerView;
******
recyclerView.setHasFixedSize(false);
LinearLayoutManager linearLayoutManager = new LinearLayoutManager(getActivity());
recyclerView.setLayoutManager(linearLayoutManager);
recyclerView.setClipToPadding(true);
recyclerView.setDefaultSwipeToRefreshColorScheme(getResources().getIntArray(R.array.google_colors));
  recyclerView.setDefaultOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener()){****}

**Comment by lichenyang1993** [comment]
I solve this problem by add com.android.support:recyclerview-v7 to the dependency
