### ISSUE TITLE
OnLoadMoreListener gets called several times

### ISSUE THREAD

**Issue by pkliang** [cymcsg/UltimateRecyclerView#27]
Hi, according to my test, the OnLoadMoreListener gets called several times when you scroll up and down the recyclerView several times.

**Comment by cymcsg** [comment]
If you scroll up and down to the last item again and again the recyclerview will call OnLoadMoreListener for many times.
In fact I think it should be adjusted by the custom method, but maybe I'll add a method to judge it.

**Comment by pkliang** [comment]
FYI: https://gist.github.com/ssinss/e06f12ef66c51252563e,  a clean solution

**Comment by mahdihijazi** [comment]
@pkliang @cymcsg please check updated solution
https://github.com/cymcsg/UltimateRecyclerView/pull/31

**Comment by cymcsg** [comment]
@mahdihijazi  Thank you very much for the useful solution.
@pkliang Please check if the method runs well.The method is on the latest dev branch.

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.
