### ISSUE TITLE
Enable load more after disabling load more Bug

### ISSUE THREAD

**Issue by hodachop93** [cymcsg/UltimateRecyclerView#272]
When I reach the end of list, I disable load more, then I refresh the list, I want to enable load more but it's not working? Please help me?

**Comment by cymcsg** [comment]
It should be enhanced in next version.Now you can only use some ugly method to do that.

**Comment by lichenyang1993** [comment]
I solved this problem ty another way.When I reached the end of the list,I just modified the loading more view's text (TextView.text) to tell user no more data

**Comment by jjhesk** [comment]
please now read #276
