### ISSUE TITLE
when i swipe headview crashed

### ISSUE THREAD

**Issue by ughome** [cymcsg/UltimateRecyclerView#273]
ArrayIndexOutOfBoundException

**Comment by cymcsg** [comment]
Have you tried in demo?

**Comment by jjhesk** [comment]
i confirmed this is the still an outstanding issue. @cymcsg  would you help me to find the location of the issue? I tried before and still not able to find it.

**Comment by cymcsg** [comment]
In my previous thinking,I do not think header could be swipe.
If we want to swipe the demo we should judge the item type in adapter.

**Comment by jjhesk** [comment]
i think i have done changes on the typing in the adapter or this may affected to the swipe capability on the code. Does it have anything to deal with the [VIEWTYPE](https://github.com/cymcsg/UltimateRecyclerView/blob/core-recode-redesign/UltimateRecyclerView/ultimaterecyclerview/src/main/java/com/marshalchen/ultimaterecyclerview/UltimateViewAdapter.java#L93-L110) @cymcsg

**Comment by jjhesk** [comment]
should be fixed again..
