### ISSUE TITLE
recode the core. 

### ISSUE THREAD

**Issue by jjhesk** [cymcsg/UltimateRecyclerView#276]
First of all, thanks to @cymcsg for your amazing bundle from other library and we have been fixing bugs so far and its been your sole effort for the majority. Here I want to give you a special thanks for our hard works. However, looking at the contribution rate. We dont see the popular of contributions from the crowds. For my view of points, it is still such an headache to look at the code in one single large file. 
I think the recyclerview has been a maze for people to add their external efforts on combining their module.

Basically, there are 
1) too many hardcoded things
2) not many generic type
3) not able to add module easily.
I have read from other libraries and found some interesting implementation yet will able to keep this library as lightweight. Maybe we can try some effort to make this library more adaptable for developer crowd. Please read up this [libray](https://github.com/eyeem/RecyclerViewTools) and give me some suggestions. Here I will response to all the previous query for the adaptable module features #222  

- [x] better control for the empty view to show or not
- [x] fix load more on grid layout issue

For this version of 0.4.0 we need to clear out all the most the popular issues from the previous posts.

1. The first thing is the loadmore issue raised by all other developers. 
2. The second thing is the grid layout issues.

**Comment by cymcsg** [comment]
I agree with you.I really think the library should be more adaptable.
Would you like to be a collaborator of the project?

**Comment by jjhesk** [comment]
can u add me in the project?

**Comment by cymcsg** [comment]
@jjhesk I have added you to the project.Hoping for your magical contribution~

**Comment by jjhesk** [comment]
started from this [branch](https://github.com/cymcsg/UltimateRecyclerView/tree/core-recode-redesign) i will start digging into grid layout manager on the core code at [this file](https://github.com/cymcsg/UltimateRecyclerView/blob/core-recode-redesign/UltimateRecyclerView/ultimaterecyclerview/src/main/java/com/marshalchen/ultimaterecyclerview/UltimateRecyclerviewViewHolder.java)

**Comment by jjhesk** [comment]
now i have done some works for the upgrades. =) 

[check here at](https://github.com/cymcsg/UltimateRecyclerView/blob/core-recode-redesign/UltimateRecyclerView/ultimaterecyclerview/src/main/java/com/marshalchen/ultimaterecyclerview/UltimateGridLayoutAdapter.java) 


#280 First is the load more issue which is now resolved.

Now this is the proper coding for enable load more on grid layout manager
```java

     super.onCreate(savedInstanceState);
        setContentView(getMainLayout());
        mToolbar = (Toolbar) findViewById(R.id.tool_bar);
        setSupportActionBar(mToolbar);
        getSupportActionBar().setDisplayShowTitleEnabled(true);
        listuv = (UltimateRecyclerView) findViewById(R.id.ultimate_recycler_view);
        mGridAdapter = new GridLayoutRVAdapter(getItems());
        mGridAdapter.setSpanColumns(columns);
        mGridLayoutManager = new BasicGridLayoutManager(this, columns, mGridAdapter);
        listuv.setLayoutManager(mGridLayoutManager);
        listuv.setHasFixedSize(true);
        listuv.setSaveEnabled(true);
        listuv.setClipToPadding(false);
        listuv.setAdapter(mGridAdapter);
        listuv.setItemAnimator(new DefaultItemAnimator());

        // mGridAdapter.setCustomLoadMoreView(LayoutInflater.from(this).inflate(R.layout.custom_bottom_progressbar, null));
        listuv.setNormalHeader(setupHeaderView());
        final Handler f = new Handler();
        listuv.setOnLoadMoreListener(new UltimateRecyclerView.OnLoadMoreListener() {
            @Override
            public void loadMore(int itemsCount, int maxLastVisiblePosition) {
                //   Log.d(TAG, itemsCount + " :: " + itemsCount);
                f.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        mGridAdapter.insert(SampleDataboxset.newListFromGen(2));
                        // listuv.disableLoadmore();
                        // listuv.disableLoadmore();
                    }
                }, 1000);
            }
        });

        listuv.enableLoadmore();

```

when you need to disable load more after done loading the items you can do this:

```java

    public void loadMore(int itemsCount, int maxLastVisiblePosition) {
                //   Log.d(TAG, itemsCount + " :: " + itemsCount);
                f.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        mGridAdapter.insert( .... );
                        listuv.disableLoadmore();
                    }
                }, 1000);
            }
```

**Comment by jjhesk** [comment]
@cymcsg can you please do some testing on the scrolling? lets test it and see if it is stable on my branch then we can publish a release for the incremental version. Cheers!

**Comment by cymcsg** [comment]
Great work! Let's try to do some test and then release them.

**Comment by jjhesk** [comment]
just tested on linearlayout and i also fixed the defects from the load more. please do more load more testing...

**Comment by jjhesk** [comment]
quick fix from zero data at the beginning. #284

**Comment by cymcsg** [comment]
Awesome work!

**Comment by jjhesk** [comment]
@cymcsg try to deploy from branch [core-recode-redesign](https://github.com/cymcsg/UltimateRecyclerView/tree/core-recode-redesign) i think its ready for 0.4.0. the only thing is the swiplist demo and there are some errors behind. you might take a look of the [code](https://github.com/cymcsg/UltimateRecyclerView/tree/core-recode-redesign/UltimateRecyclerView/app/src/main/java/com/marshalchen/ultimaterecyclerview/demo/swiplistdemo)

**Comment by cymcsg** [comment]
Great work!
I have noticed that problem in ``SwipeListViewExampleActivity`` and some problem in the Mainactivity when I swipe the first item.

**Comment by cymcsg** [comment]
I do not have enough time to fix the bug in ``SwipeListViewExampleActivity`` in these days so I think it's a good idea to release 0.4.0 with this problem which will be fixed in next version.
Thank you for your great work.If you like we can also talk about something via Email.

**Comment by jjhesk** [comment]
@cymcsg  yes i can take up your work and fix the possible bugs

**Comment by jjhesk** [comment]
should be fixed again.. on v0.5.0
