### ISSUE TITLE
scrollVerticallyToPosition(0) and parallax header

### ISSUE THREAD

**Issue by rittjom** [cymcsg/UltimateRecyclerView#277]
If you call the scrollVerticallyToPosition(0) function in the recyclerview, after it the parallax header is not at the right position. Or is there any other way to go to the top of the recyclerview??

**Comment by jjhesk** [comment]
There is need to fix this. It maybe needing to work on the observable object to making sure the header can be located at the right position again. We need some more help to understand how this work..

**Comment by rittjom** [comment]
Maybe I found the reason...
There's a variable **mTotalYScrolled**. On every **onScrolled()** event of the RV this variable is incremented or decremented... depending on the scroll direction.

When you call **scrollVerticallyToPosition(0)** this variable is incremented with += 0. So the old value of **mTotalYScrolled** is still used and passed to the **translateHeader()** function and it sets the **setClipY()** with this wrong offset to the canvas.


So i think the right behavoir would be if the **scrollVerticallyToPosition(x)** function reset the **mTotalYScrolled** variable to the right value...

**Comment by jjhesk** [comment]
have you forked the fixed yet?

**Comment by jjhesk** [comment]
it should be already fixed.
