### ISSUE TITLE
Although call disableLoadmore method, load more view will still show if item count is more than 3 

### ISSUE THREAD

**Issue by bitjjj** [cymcsg/UltimateRecyclerView#28]
Because when calling disableLoadmore method, customLoadMoreView will still be set an empty view(empty_progressbar.xml). But if recycle view need show load more view you use the following clauses:

if (mAdapter.getAdapterItemCount() >= showLoadMoreItemNum && mAdapter.getCustomLoadMoreView() != null
                            && mAdapter.getCustomLoadMoreView().getVisibility() == View.GONE) {
                        mAdapter.getCustomLoadMoreView().setVisibility(View.VISIBLE);
                    }
                    if (mAdapter.getAdapterItemCount() < showLoadMoreItemNum && mAdapter.getCustomLoadMoreView() != null) {
                        mAdapter.getCustomLoadMoreView().setVisibility(View.GONE);
                    }

You can see the if clause can still be true, is that right?

**Comment by cymcsg** [comment]
Do you mean if you ``disableLoadmore`` and you want to enableloadmore again you find there was a bug in the recyclerview?

**Comment by bitjjj** [comment]
yes

**Comment by cymcsg** [comment]
The ``disableLoadmore`` method really has some bugs in current version.I'll try to fix most of them in the future.

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue. @bitjjj
