### ISSUE TITLE
Scrollbar does not work with CustomUltimateRecyclerview

### ISSUE THREAD

**Issue by Aqua-Ye** [cymcsg/UltimateRecyclerView#281]
The scrollbar does not appear when using CustomUltimateRecyclerview

**Comment by jjhesk** [comment]
i have not look into this piece of CustomUltimateRecyclerview yet. Can you show me your code?

**Comment by Aqua-Ye** [comment]
Fixed in 806c2a75883ac477a3e09a9bd8075e88b0fc4cfe

**Comment by cymcsg** [comment]
Maybe it's not a bug.But it's better to add some custom feature.
