### ISSUE TITLE
Where is the code for the leave-behind example?

### ISSUE THREAD

**Issue by awhlee** [cymcsg/UltimateRecyclerView#289]
The sample app implements a different from of a leave behind but I'm looking for the app that is profiled here: https://github.com/cymcsg/UltimateRecyclerView/wiki/Swipe-to-dismiss.  Full swipe, multiple buttons....

Thanks!

**Comment by jjhesk** [comment]
[this is the example here](https://github.com/cymcsg/UltimateRecyclerView/blob/core-recode-redesign/UltimateRecyclerView/app/src/main/java/com/marshalchen/ultimaterecyclerview/demo/swipelist/SwipeListViewExampleActivity.java)
please help us out to add the sample code into the wiki thx!! @awhlee
