### ISSUE TITLE
UltimateRecyclerView Inside NestedScrollView Below Textview

### ISSUE THREAD

**Issue by aymane-mzily** [cymcsg/UltimateRecyclerView#290]
Hi
When i want to put UltimateRecyclerView inside NestedScrollView and below a TextView not displaying items this is my code : 
`<?xml version="1.0" encoding="utf-8"?>

<android.support.v4.widget.NestedScrollView
    android:fillViewport="true"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:wheel="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context="com.aymsou.stories.StoryDisplay"
    tools:showIn="@layout/activity_story_display">

    <LinearLayout
        android:layout_centerVertical="true"
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.pnikosis.materialishprogress.ProgressWheel
            android:layout_marginTop="15dp"
            android:id="@+id/txt_loader"
            android:layout_width="80dp"
            android:layout_height="80dp"
            android:layout_gravity="center"
            wheel:matProg_barColor="@color/colorAccent"
            wheel:matProg_progressIndeterminate="true" />

        <TextView
            android:id="@+id/articleContents"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="right"
            android:textColor="@android:color/black"
            android:lineSpacingExtra="8dp"
            android:paddingLeft="@dimen/text_margin"
            android:paddingRight="@dimen/text_margin"
            android:paddingTop="32dp"
            />

        <TextView
            android:id="@+id/theComments"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@+id/storyCts"
            android:textColor="@android:color/black"
            android:text="@string/comments"
            android:visibility="gone"
            android:paddingRight="@dimen/text_margin"
            android:paddingBottom="@dimen/text_margin"
            android:gravity="right"
            android:textSize="18dp"/>

        <com.marshalchen.ultimaterecyclerview.UltimateRecyclerView
            android:layout_below="@+id/theComments"
            android:id="@+id/commentsList"
            android:layout_width="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            android:layout_height="wrap_content"/>

    </LinearLayout>

</android.support.v4.widget.NestedScrollView>`

`final CustomLinearLayoutManager layoutManager = new CustomLinearLayoutManager(ctx, LinearLayoutManager.VERTICAL, false);
commentsList.setLayoutManager(layoutManager);
final CommentsAdapter adapter = new CommentsAdapter(comments, ctx, commentsList);
commentsList.setAdapter(adapter);`

The problem is UltimateRecyclerView not wrapping content inside a scrollview any idea ?

**Comment by jjhesk** [comment]
because they both have scrolling gesture in URV and the scrollview. try not to overlap both module into one place.

**Comment by aymane-mzily** [comment]
@jjhesk Thanks , But i want to make Reyclerview below Contents ( Article Comments )
