### ISSUE TITLE
minSdkVersion 15

### ISSUE THREAD

**Issue by Dalanie** [cymcsg/UltimateRecyclerView#297]
Did you really have to change the minSdkVersion to 15? I know that 9 is pretty old and most of the people won't need it. However, there are people who still rely on this old version (such as me). What changes did you make that require a minSdkVersion of 15?

**Comment by jjhesk** [comment]
i think there will be a refactors for the nineoldandroid lib so this will make the minsdk to increase.

**Comment by Dalanie** [comment]
And why not stick with nineoldandroid? :(

**Comment by jjhesk** [comment]
we still have the older branch from the before refactoring but the older api is very buggy tho.

**Comment by Dalanie** [comment]
the older branch is unfortunatelly very buggy as you stated out.. nineold
was working fine as it is. I need to switch to a different lib if you
decide to stay min sdk 15 +. Thanks for the quick answers

**Comment by jjhesk** [comment]
sorry about that. i guess there are alot of simple libraries out there can sort it out..
