### ISSUE TITLE
if no header and not data(list is null) and enableLoadmore, it will crash

### ISSUE THREAD

**Issue by OVERSKY2003** [cymcsg/UltimateRecyclerView#301]
if no header and not data(list is null), but enableLoadmore,  offset=1 in getItemCount(). It will call createViewHolder(ViewGroup parent, int viewType) in RecyclerView class. the holder is null and crashes.

        public final VH createViewHolder(ViewGroup parent, int viewType) {
            TraceCompat.beginSection(TRACE_CREATE_VIEW_TAG);
            final VH holder = onCreateViewHolder(parent, viewType);
            holder.mItemViewType = viewType;
            TraceCompat.endSection();
            return holder;
        }

    @Override
    public int getItemCount() {
        int offset = 0;
        if (hasHeaderView()) offset++;
        if (enableLoadMore()) offset++;
        // boolean a = enableLoadMore();
        // boolean b = hasHeaderView();
        return getAdapterItemCount() + offset;
    }

![image](https://cloud.githubusercontent.com/assets/4005701/13045486/8f6bae32-d40e-11e5-8734-1a00923a154b.png)

**Comment by jjhesk** [comment]
thanks for reporting.

**Comment by OVERSKY2003** [comment]
Actually, I found EmptyView could not work in 0.4.0. I revert to 0.3.18. it is ok

**Comment by jjhesk** [comment]
for the new behavior, 
if it is loading from the initialization the empty view should not be shown and let the loading progress bar shown instead.

**Comment by OVERSKY2003** [comment]
what  do you mean that "let the loading progress bar shown instead"?

**Comment by jjhesk** [comment]
two situations
1. data is exist for the adapter is use and the list can be thrown into the adapter.
2. data is not loaded before the the adapter to be initialize. First initialize the adapter and wait for the data to be loaded and insert into the adapter.

**Comment by OVERSKY2003** [comment]
There is no data at all. What I want is to show empty view to let user know there is no data. what can I do that in 0.4.0

**Comment by jjhesk** [comment]
I think there should be a empty view policy for the adapter.
lets think of these naming..

NETWORK_DATA - assume there is no data to show at the initial stage and it does not show the empty view at firs. Wait until the network access is complete then it will show the empty view if there is no data contains in the array.
PRESET_DATA - show empty view to let user know there is no data when first the adapter is initialized. 
DEFAULT - NETWORK_DATA
adapter.emptyViewPolicy( DEFAULT )

**Comment by jjhesk** [comment]
now i have updated the work and resolve the issue in 
linear + no header + load more enable

#303

**Comment by OVERSKY2003** [comment]
when will this fix(#303) be released?

**Comment by jjhesk** [comment]
yes. im still waiting for @cymcsg  to release it.

**Comment by OVERSKY2003** [comment]
The release includes "adapter.emptyViewPolicy(DEFAULT)", right?

**Comment by jjhesk** [comment]
i will release the sample code today @OVERSKY2003 please also see the latest update #314

**Comment by OVERSKY2003** [comment]
where and how can I see the sample code?
please let me know when it release. If load more and empty view issue are fixed, I will use this library in my production APP.

**Comment by jjhesk** [comment]
this is fixed now #323  check with this update

**Comment by jjhesk** [comment]
@OVERSKY2003 have you check with the new version yet? does it work?
