### ISSUE TITLE
Recyclerview-v7-23.1.1 upgrade progress

### ISSUE THREAD

**Issue by jjhesk** [cymcsg/UltimateRecyclerView#314]
Since v23.1.1 has been phrasing out for a while, i decided to upgrade this library to adapter the latest convention. This will be a long track progress and it needs a new branch for this big mess. 
Welcome to make your [PR for enhancement]() of this project. This upgrade is based on [his work](https://github.com/gabrielemariotti/RecyclerViewItemAnimators/tree/master/library/src/main/java/it/gmariotti/recyclerview)

@alafighting 
This will answer the question from #288 

Please follow the latest publishing aar on jcenter. [ ![Download](https://api.bintray.com/packages/jjhesk/maven/MenuURV/images/download.svg) ](https://bintray.com/jjhesk/maven/MenuURV/_latestVersion)

follow by the gradle code
```gradle

repositories {
    jcenter()
    maven { url "http://dl.bintray.com/jjhesk/maven" }
}
{
compile 'com.hkm.slidingmenulib:libmenu:0.4.7'
}
```

**Comment by jjhesk** [comment]
@cymcsg  can you issue a separate library and name it as v23.1.1

**Comment by cymcsg** [comment]
@jjhesk I'm not quite sure what about ``a separate library``.Could you explain it more clearly?Thank you

**Comment by jjhesk** [comment]
now i have worked on the update of the package and it is up running

```gradle
{
compile 'com.hkm.slidingmenulib:libmenu:0.4.1'
}
```

**Comment by jjhesk** [comment]
i will have another update for this library. Since this library was not using API v23.1.1 @cymcsg  there were alot of the things that doesnt support in APIv23.0.1. There will be a big change from the animation library. For this reason I removed the internal library for animation and import the compile package from `  compile 'jp.wasabeef:recyclerview-animators:2.2.0'` and that was not compiled in v23.1.1 below.  Please also see the readme file on https://github.com/wasabeef/recyclerview-animators

**Comment by jjhesk** [comment]
the latest pull for the branch #322 this will cover the animation upgrade for v23.1.1 and above and fixed some loadmore and emptyview control options.

**Comment by cymcsg** [comment]
Thank you.I got it. 
Do you think that we need a v23.0.1 library rather than upgrade this library to v23.0.1 in a new version?

**Comment by jjhesk** [comment]
keep the old branch and name it as api 23.0.1 as we may need to go back and retouch the code for older android devices and we will merge v23.1.1 into master as this will be all future library will be used.

**Comment by cymcsg** [comment]
I have release a branch which named ``RecyclerviewV22`` for the old version.

**Comment by jjhesk** [comment]
Thats good. Now i got the ultimate recycler ready for API 23.1.1 and above with this update #323.

**Comment by jjhesk** [comment]
There are known issue related to loadmore view and once it is visible `GONE` from the recyclerview.

**Comment by alafighting** [comment]
给力！
It is awesome!
