### ISSUE TITLE
OnScrollListener - RecyclerView Y Translation

### ISSUE THREAD

**Issue by rikochet** [cymcsg/UltimateRecyclerView#33]
I am using the OnScrollListener to hide the Toolbar when scrolling.. This functions correctly with the stock RecyclerView, however when using UltimateRecyclerView component, the RecyclerView doesn't translate upwards with the Toolbar, instead it just crops the content.

Any ideas as to how to resolve this? TIA.

Here's how it looks.. 
![Actual Result]
(https://camo.githubusercontent.com/29266624d024818bf2769fbecb63a0c05199f95c/68747470733a2f2f7777772e756c747261696d672e636f6d2f696d616765732f4d6179303432303135323331312e676966)

Here's how it should look..
![Desired Effect]
(https://camo.githubusercontent.com/189c843aca53b2a6763216f72b2b364b81871acc/68747470733a2f2f6d7a677265656e2e6769746875622e696f2f696d616765732f322f6e6f736e61702e676966)

**Comment by cymcsg** [comment]
Do you use custom ``OnScrollListener`` for show and hide toolbar or use the method in UltimateRecyclerview? I think maybe there are some conflicts if you use your custom scroll listener.
I want to know what kind of  function you want in custom scroll listener .
Thank you.

**Comment by wrik** [comment]
@cymcsg thanks, I hadn't noticed the built-in method! nice one!

Now I am using the following code:
```
 @Override
            public void onUpOrCancelMotionEvent(ObservableScrollState observableScrollState) {
                if (observableScrollState == ObservableScrollState.DOWN) {
                    mRecyclerView.showToolbar(mToolbar, mRecyclerView, metrics.heightPixels);
                } else if (observableScrollState == ObservableScrollState.UP) {
                    mRecyclerView.hideToolbar(mToolbar, mRecyclerView, metrics.heightPixels);
                } else if (observableScrollState == ObservableScrollState.STOP) {
                }
            }
```

I have run in to the following issue, whereby the the RecyclerView moves upwards leaving a blank gap at the bottom of the screen.

(http://s28.postimg.org/qbui34j0r/May_10_2015_11_54.gif)

**Comment by meliksah** [comment]
Basically you must use frame layout

**Comment by jjhesk** [comment]
i have done some sample code in another project that does this.. 

```java


    @Subscribe
    public void onEvent(ResponsiveBaring.ScrollOnMove scroll) {
        if (scroll.isActionMove()) {
            mTab.setTranslationY(-scroll.getDistance() + toolBarHeight);
        }
        if (scroll.isActionShow()) {
            mTab.animate().translationY(toolBarHeight).setInterpolator(new DecelerateInterpolator(2)).start();
        }
        if (scroll.isActionHide()) {
            mTab.animate().translationY(0).setInterpolator(new AccelerateInterpolator(2)).start();
        }
    }

```
