### ISSUE TITLE
瀑布流StaggeredGridLayoutManager时设置normalheader也为瀑布流的样式

### ISSUE THREAD

**Issue by stepforward** [cymcsg/UltimateRecyclerView#336]
瀑布流StaggeredGridLayoutManager时设置normalheader也为瀑布流的样式。可否让header依然为LinearLayoutManager时的样式？也就是说，无论recyclerview如何改变LayoutManager，header保持不变

**Comment by lywhlao** [comment]
同问，我也遇到这个问题。

**Comment by jjhesk** [comment]
StaggeredGridLayoutManager is not fully supported yet. But i can look into this. @stepforward

**Comment by lywhlao** [comment]
I find a solution:
1.First Step:add the HeaderView to the recyclerView(user addHeaderView());
2.in Adapter,change the HeaderView's layout:
`  if(position==0){
            //1.针对headView
            StaggeredGridLayoutManager.LayoutParams layoutParams = new StaggeredGridLayoutManager.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
            layoutParams.setFullSpan(true);
            holder.itemView.setLayoutParams(layoutParams);
        }`
@stepforward

**Comment by stepforward** [comment]
Or we can add this method to your adapter:

@Override
public void onViewAttachedToWindow(RecyclerView.ViewHolder holder) {
    super.onViewAttachedToWindow(holder);
    ViewGroup.LayoutParams lp = holder.itemView.getLayoutParams();
    if(lp != null
      && lp instanceof StaggeredGridLayoutManager.LayoutParams
      && holder.getLayoutPosition() == 0) {
  StaggeredGridLayoutManager.LayoutParams p = (StaggeredGridLayoutManager.LayoutParams) lp;
  p.setFullSpan(true);
    }
}
