### ISSUE TITLE
I can't use setOnRefreshListener

### ISSUE THREAD

**Issue by gushoubang** [cymcsg/UltimateRecyclerView#34]

**Comment by gushoubang** [comment]
我想使用下拉刷新，加载更多，但是setOnRefreshListener这个方法就报错

**Comment by cymcsg** [comment]
Could you show more details of your code? I think the method in demo works fine.

**Comment by t0astt** [comment]
@gushoubang please provide the code you are trying to work with. Something like the following works fine for me:

mUltimateRecyclerView.setDefaultOnRefreshListener(new SwipeRefreshListener.OnRefreshListener() {
     @Override
     public void onRefresh() {
         // do your refresh;
     }
});

**Comment by gushoubang** [comment]
ok,let me have a try

**Comment by gushoubang** [comment]
It is OK.
Set swipe to refresh: like this

mUltimateRecyclerView.setDefaultOnRefreshListener

mUltimateRecyclerView.setDefaultOnRefreshListener(new SwipeRefreshListener.OnRefreshListener() {
@Override
public void onRefresh() {
// do your refresh;
}
});

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.
