### ISSUE TITLE
Error:(1) No resource found that matches the given name (at 'layout_height' with value '@dimen/header_height').

### ISSUE THREAD

**Issue by ashmin91** [cymcsg/UltimateRecyclerView#348]
Error:(1) No resource found that matches the given name (at 'layout_height' with value '@dimen/header_height').

**Comment by igrrik** [comment]
same thing

**Comment by jjhesk** [comment]
can u show me the code

**Comment by OVERSKY2003** [comment]
miss the '@dimen/header_height' definition in  ../UltimateRecyclerView/ultimaterecyclerview/src/main/res/values/dimens.xml

![image](https://cloud.githubusercontent.com/assets/4005701/14133949/f2ffd060-f685-11e5-8aa4-fc5abc246038.png)

**Comment by jjhesk** [comment]
i have done the search and there isnt anything will be using this configuration.
