### ISSUE TITLE
the LoadMoreView cann't show

### ISSUE THREAD

**Issue by monster-** [cymcsg/UltimateRecyclerView#349]
my code:
meetPartyGroupAdapter.enableLoadMore(true);
meetPartyGroupAdapter.setCustomLoadMoreView(LayoutInflater.from(getActivity()).inflate(R.layout.custom_bottom_progressbar,null));
recyclerView.setOnLoadMoreListener(new UltimateRecyclerView.OnLoadMoreListener() {
            @Override
            public void loadMore(int itemsCount, int maxLastVisiblePosition) {
                Log.e("=====loadMore","loadMore=======");
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        recyclerView.disableLoadmore();
                    }
                }, 2000);
            }
        });

**Comment by jjhesk** [comment]
you dont need to put `meetPartyGroupAdapter.enableLoadMore(true);`

**Comment by jitongkai** [comment]
i have this problem too!

**Comment by jjhesk** [comment]
please double check with the setups at [here](https://github.com/cymcsg/UltimateRecyclerView/blob/master/UltimateRecyclerView/app/src/main/java/com/marshalchen/ultimaterecyclerview/demo/loadmoredemo/DebugLoadMoreActivity.java)

**Comment by jjhesk** [comment]
try `setadapter` as the last step
