### ISSUE TITLE
Different layout is not supported in UltimateViewAdapter?

### ISSUE THREAD

**Issue by sachil** [cymcsg/UltimateRecyclerView#35]
I try to create an adapter which extends UltimateViewAdapter,and I want to load different layout file.So I overwrite the function:getItemViewType(),but I find out that the function:onCreateViewHolder() only have one paramater,not contain viewType.
Please give me some suggesttions,thanks a lot.

**Comment by snezdoliy** [comment]
Hi, first of all Thanks! You are doing a great job with this lib!
I was using SuperRecyclerView before, and now wanted to switch to UltimateRecyclerView as it has more nice features I need. Currently this issue prevents me from switching to UltimateRecyclerView as I need to support different layouts in my RecyclerView. Could you please advice any workarounds for now? I tried testing app quickly with `public void setAdapter(Adapter adapter)` method which is deprecated now, it works, but I am loosing all the benefits :( of the view. I would be happy to hear any suggestions of how to solve this issue.

**Comment by cymcsg** [comment]
Thank you for giving such useful advice.I'll try to support different layout in UltimateViewAdapter and I hope someone can help me to perfect the project.

**Comment by jjhesk** [comment]
You will need these [setups](https://github.com/HKMOpen/RecyclerView-MultipleViewTypesAdapter/tree/master/library/src/main/java/com/yqritc/recyclerviewmultipleviewtypesadapter) on the base or you can just include the library into this project. It is just up to your decision.

On the implementation, you need to let user to design their own type as written in [sample](https://github.com/HKMOpen/RecyclerView-MultipleViewTypesAdapter/blob/master/sample/src/main/java/com/yqritc/recyclerviewmultipleviewtypesadapter/sample/adapter/EnumMapAdapter.java) and there is better to support the default viewType as from google AdMob.

**Comment by cymcsg** [comment]
In the latest version of UltimateRecyclerview, there is a ``UltimateDifferentViewTypeAdapter`` which can help use different viewholder in an adapter . I think it could help you about the problem.

**Comment by sachil** [comment]
OK,I will have a try,thank you very much!
