### ISSUE TITLE
bug when use CoordinatorLayout and UltimateRecyclerView with PtrFrameLayout?

### ISSUE THREAD

**Issue by Yellup** [cymcsg/UltimateRecyclerView#352]
simple XML:
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <android.support.design.widget.CoordinatorLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/main_content"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/driver">

        <android.support.design.widget.AppBarLayout
            android:id="@+id/appbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <View
                android:id="@+id/nv_bar"
                android:layout_height="46dip"
                android:background="?attr/colorPrimary"
                style="@style/Layout_Full_Width"
                app:layout_scrollFlags="scroll|enterAlways" />

        </android.support.design.widget.AppBarLayout>

        <android.support.v4.view.ViewPager
            android:id="@+id/viewpager"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:overScrollMode="never"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"/>

    </android.support.design.widget.CoordinatorLayout>
</RelativeLayout>

and the ViewPager just contains a UltimateRecyclerView that with PtrFrameLayout,
when app start, the UltimateRecyclerView in the top without scroll, and now scroll up(hand ↑),it will happen touch conflict, is a bug or my error usage?

**Comment by jjhesk** [comment]
it is still under construction for bug fixing.

**Comment by Yellup** [comment]
i fix it whit some change of UltimateRecyclerView by let UltimateRecyclerView implements NestedScrollingParent and change some sourecode to Adapted my project, but it's not elegant
