### ISSUE TITLE
setNormalHeader or setParallaxHeader（view） the header did not appear

### ISSUE THREAD

**Issue by lkwjohn** [cymcsg/UltimateRecyclerView#355]
```
View headerView = LayoutInflater.from(context).inflate(R.layout.header, ultimateRecyclerView.mRecyclerView, false);
ultimateRecyclerView.setNormalHeader(headerView);
```

Used this version of the library:
maven { url "http://dl.bintray.com/jjhesk/maven" }
compile 'com.hkm.slidingmenulib:libmenu:0.4.7'

**Comment by lkwjohn** [comment]
the issue is similar to #231. It seems like it's not fixed.

**Comment by lkwjohn** [comment]
Hi, 

managed to resolved it after looking at the setAdapterInternal which i realise that the mAdapter.setCustomHeaderView(mHeader); is only called once after user have set the adapter. Thus, i shifted the set header before setAdapter and that work as compare to the version of compile 'com.marshalchen.ultimaterecyclerview:library:0.3.11' .

**Comment by jjhesk** [comment]
right. set adapter is the last step to setup the recycler view.
