### ISSUE TITLE
UltimateAdapter

### ISSUE THREAD

**Issue by wangmingjob** [cymcsg/UltimateRecyclerView#36]
hello，cymcsg，工具集成的很不错，赞一个，不过里面自带的UltimateAdapter并没有做精简，还是和原生一样需要码很多句，我发现一个不错的adapter，https://github.com/StanKocken/EfficientAdapter

**Comment by cymcsg** [comment]
Thank you for your advice.
The UltimateRecyclerview provides many effects but the adapter is similar as the normal one in the current version.
I'll try to make it easier to use in the future.

**Comment by Wolftein** [comment]
+1 looking forward on this update.

**Comment by jjhesk** [comment]
+1

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.
