### ISSUE TITLE
customLoadMoreItemView not set UltimateViewAdapter

### ISSUE THREAD

**Issue by serkanucar** [cymcsg/UltimateRecyclerView#365]
customLoadMoreItemView not set in UltimateViewAdapter  alwasy null.
```java
protected void revealDispatchLoadMoreView() {
        if (customLoadMoreItemView != null) {
            if (customLoadMoreItemView.getVisibility() != View.VISIBLE) {
                customLoadMoreItemView.setVisibility(View.VISIBLE);
            }
        }
    }
```

My code
```java
mRecyclerView.hideEmptyView();
mRecyclerView.setLoadMoreView(R.layout._view_list_view_bottom_progressbar);
mRecyclerView.setOnLoadMoreListener(new UltimateRecyclerView.OnLoadMoreListener() {
	@Override
	public void loadMore(int itemsCount, final int maxLastVisiblePosition) {
		new Handler().postDelayed(new Runnable() {
			@Override
			public void run() {                       
				getData();
			}
		}, 500);
	}
});

getData() {

		if (mPageIndex == 0) {
			mRecyclerView.disableLoadmore();
		}
		else {
			mRecyclerView.reenableLoadmore();
		}

		mMainAllAdapter.insertInternal(data, mData);

		if (mData.size() >= mTotalRecordCount){
			mRecyclerView.disableLoadmore();
		}
		else {
			mRecyclerView.reenableLoadmore();
		}

		if (mMainAllAdapter.getItemCount() == 0) {
			mRecyclerView.showEmptyView();
		}

		mLoadData = true;

		mPageIndex++;
}
```

**Comment by jjhesk** [comment]
You need to explain more of ur issue. How does it produce this issue?

**Comment by serkanucar** [comment]
Exactly what do you want. I wrote the above code sample

**Comment by serkanucar** [comment]
I Think problem is here

      VH viewHolder = newFooterHolder(customLoadMoreView);
       customLoadMoreView is not null but
       viewHolder is null always

**Comment by jjhesk** [comment]
There should be a good mechanism to check for the null on `customLoadMoreView`. Yes, you need manually initialize the footer view holder in your implementation. With this architecture design to give developer alot more extendibility for their own and all other heavy lifting are done in this library.

**Comment by serkanucar** [comment]
Can you give example for Loadmore 
easyRegularAdapter,Ultimate View Adapter,UltimateDifferentViewType Adapter

Thank you.

**Comment by castrojr913** [comment]
The same issue happens me
