### ISSUE TITLE
set Emptyview by code. And Set listener to Emptyview.????

### ISSUE THREAD

**Issue by JSBerrocoso** [cymcsg/UltimateRecyclerView#37]

**Comment by cymcsg** [comment]
Do you mean you want set a emptyview even the adapter already have something?

**Comment by jjhesk** [comment]
I think i have also seen this issue coming.when there is no items in the list view. The load more progressbar appear with the loadmore set true. The thing is that there should show up the something else in custom layout to notify the end user that there is nothing to show. There should be a support in the UltimateRecycleView thing wrapped. @cymcsg let me know if u have found the way to enhance it.


The logic is that
1) loadmore view is enabled
2) empty view is also enabled and it should be called manually from user logic when the api request for data loading is done and there is nothing in the list object.

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.
