### ISSUE TITLE
Cannot extend UltimateRecyclerviewViewHolder as it is protected

### ISSUE THREAD

**Issue by sergii-frost** [cymcsg/UltimateRecyclerView#38]
Hi, I am trying to integrate UltimateRecyclerView into my project, and I am not able to extend my custom ViewHolder from `UltimateRecyclerviewViewHolder` as it is protected class in `UltimateViewHolder`. 

It would be good also if adapter could be based on generics, to that I could use it in same way as `RecyclerView.Adapter` and specify my custom ViewHolder class there.

**Comment by cymcsg** [comment]
Thank you very much for giving the advice.
In fact there are some useful method based on the adapter so I found it hard to use only  ``RecyclerView.Adapter`` so I use a custom ``UltimateViewAdapter``.
I'll change ``UltimateRecyclerviewViewHolder`` to public in dev branch soon.But I know it do not solve many problems.I'll try to make the adapter more flexible to use and I hope to hear your good advice.

**Comment by snezdoliy** [comment]
@cymcsg Thank you for quick feedback! If you need any testing or contribution, please let me know :)

**Comment by cymcsg** [comment]
In the latest version of UltimateRecyclerview, there is a ``UltimateDifferentViewTypeAdapter`` which can help use different viewholder in an adapter . I think it could help you about the problem.

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.
