### ISSUE TITLE
ViewStub must have a valid layoutResource

### ISSUE THREAD

**Issue by lleeaaff** [cymcsg/UltimateRecyclerView#388]
at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:5747)

**Comment by lleeaaff** [comment]
不能刷新

**Comment by SeyedAliFarjaD** [comment]
must add a Empty view
like  mRecyclerView.setEmptyView(R.layout.empty_progressbar,0);

that error is for return null as empty view and get  ViewStub must have a valid layoutResource expection

**Comment by cymcsg** [comment]
Without showing more code,I can hardly help you solve the problem.
