### ISSUE TITLE
EmptyView  does not appear 

### ISSUE THREAD

**Issue by Snakeice** [cymcsg/UltimateRecyclerView#399]
Hi,

I'm using fragments when there are no items to emptyview is empty.

I've tried the pro inflator in two ways:
```JAVA
         recyclerView.setInflater(LayoutInflater.from(view.getContext()));
         recyclerView.setInflater(inflater);
```
but none worked...   : [

I´m using version 0.5.92

**Comment by Snakeice** [comment]
She appears briefly and then disappears*

**Comment by Snakeice** [comment]
I found the problem :]

**Comment by restor1** [comment]
What was the problem? (having the same issue here)

**Comment by Snakeice** [comment]
Please see #401 that solved my problem, always entered as the variable was never true...

**Comment by Snakeice** [comment]
Try use > compile 'com.github.Snakeice:UltimateRecyclerView:c9adbddc2f'
