### ISSUE TITLE
这是个依赖包,有没有demo运行起来看效果啊

### ISSUE THREAD

**Issue by tangchao0106** [cymcsg/UltimateRecyclerView#404]
这是个依赖包,有没有demo运行起来看效果啊

**Comment by tangchao0106** [comment]
运行起来之后,怎么到处报错啊,怎么还有4000星啊

**Comment by weiqichang** [comment]
效果很棒，但是有很多bug!

**Comment by cymcsg** [comment]
Some bugs are due to the new version of support library of Google.
We'll try to fix them in the future.
