### ISSUE TITLE
Fling stuck issue

### ISSUE THREAD

**Issue by smelfungus** [cymcsg/UltimateRecyclerView#465]
Hi there!
Here is a nasty issue with fling stuck, reproducible even with built-in samples.

- Library version: 0.7.2
- Devices: Nexus 5X, Pixel XL
- Android version: 7.1.2

Recorded issue video:
https://drive.google.com/file/d/0B3vdAkni3quad3RwNENuZHZwWVU/view?usp=sharing

As you can see issue is spawning on **0:03**, **0:12**, **0:20**.
Please note, that there were plenty of items already added to adapter so it's not related to load more triggering and it's also spawning in both directions.
Please, download the video in case of poor web player quality.

**Comment by cymcsg** [comment]
Do you mean the problem is the recyclerview stuck when it already get to the bottom of the recyclerview?

**Comment by DummyCo** [comment]
@cymcsg as you can see scrolling accidentally stops and overscroll effect appears even when there are plenty items to scroll through. You can also notice it via scrollbar position on the video.
