### ISSUE TITLE
Found older version Glide, please update glide version

### ISSUE THREAD

**Issue by Yellu** [cymcsg/UltimateRecyclerView#484]

**Comment by Yellu** [comment]
When can I see the expected changes in master branch?

**Comment by cymcsg** [comment]
I'll try to merge it into master branch as soon as possible after the ci check has passed

**Comment by Yellu** [comment]
Okay, thank you

**Comment by Yellu** [comment]
Hi,
The library is too good, but I am facing too difficult to use the library.

Please help me.

On Tue, Feb 27, 2018 at 2:00 PM, Yellappa Pinnemcherla <yelluaprdc@gmail.com

**Comment by Yellu** [comment]
Hi cymcsg,

Please update the *support library* *versions* and *Glide* *library*
*version* to the latest.
While generating signed apk in my project getting so many conflicts and not
able to enable proguard.

Please help me, thanks in advance




On Wed, Mar 7, 2018 at 12:15 AM, Yellappa Pinnemcherla <yelluaprdc@gmail.com
> wrote:

> Hi,
> The library is too good, but I am facing too difficult to use the library.
>
> Please help me.
>
> On Tue, Feb 27, 2018 at 2:00 PM, Yellappa Pinnemcherla <

**Comment by Yellu** [comment]
Hi, please check it, Travis passed.

**Comment by Yellu** [comment]
Please merge my commits into the master branch.

On Mon, Mar 12, 2018 at 3:11 PM, Yellappa Pinnemcherla <yelluaprdc@gmail.com

**Comment by Yellu** [comment]
Hi, When can I see the expected changes in library


On Mon, Mar 12, 2018 at 3:45 PM, Yellappa Pinnemcherla <yelluaprdc@gmail.com
> wrote:

> Please merge my commits into the master branch.
>
> On Mon, Mar 12, 2018 at 3:11 PM, Yellappa Pinnemcherla <
