### ISSUE TITLE
Custom OnScrollListener can be separate?

### ISSUE THREAD

**Issue by KingWu** [cymcsg/UltimateRecyclerView#49]
Just try to integrate QuickReturn library with this library.
https://github.com/lawloretienne/QuickReturn

I found that Custom OnScrollListener and Load More OnScrollListener cannot use at the same time.

**Comment by cymcsg** [comment]
I think hiding and showing toolbar and FAB is kind of QuickReturn.Maybe QuickReturn library has more features.

If you want to use custom OnScrollListener,you must achieve the loadingmore feature by yourself as the loading more feature uses OnScrollListener
