### ISSUE TITLE
Gradle Sync Failed! Error: Failed to resolve: library

### ISSUE THREAD

**Issue by RJHsiao** [cymcsg/UltimateRecyclerView#492]
Hi there,

I'm Trying to upgrade UltimateRecyclerView in my project from v0.7.3 to v0.7.5, but always failed on gradle sync.

The build.gradle looks like: 
```gradle
repositories {
    jcenter()
}
dependencies {
    ...
    implementation 'com.marshalchen.ultimaterecyclerview:library:0.7.5'
}
```
The Error message: 
```
Failed to resolve: library
```

I tried to invalidate cache in android studio, but the error still happened.
What can i do to solve this issue?
Thanks.

**Comment by cymcsg** [comment]
```gradle
compile 'com.marshalchen.ultimaterecyclerview:library:0.7.5'
```
for gradle , or 
```maven
<dependency>
  <groupId>com.marshalchen.ultimaterecyclerview</groupId>
  <artifactId>library</artifactId>
  <version>0.7.5</version>
  <type>pom</type>
</dependency>
``` 
for maven

**Comment by RJHsiao** [comment]
@cymcsg Gradle sync still failed. The error message has become to 

```
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Failed to resolve: library
```

P.S. I'm using Android Studio 3.1.3 with Android Plugin for Gradle 3.1.3.

**Comment by cymcsg** [comment]
Sorry for that. I'll try to find out the solution.   
How about if you try to use 0.7.0 version? Is the same error?

**Comment by RJHsiao** [comment]
@cymcsg Gradle sync fine when change version to  0.7.0.

BTW, I'm using Glide v4.7.1 in my project right now, so building project will failed.

**Comment by cymcsg** [comment]
Could you use 0.7.6 for another try? Thanks a lot.
