### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by vanshg** [cymcsg/UltimateRecyclerView#496]
It would be great if you could migrate this library to using AndroidX. Should be a very simple change by way of just letting Android Studio do the whole migration for you

**Comment by cymcsg** [comment]
Thanks @vanshg . I think it's a great idea to use AndroidX for the latest trending. However as I am not focus on Android development for current stage, I wish someone can help me do the work.

**Comment by vanshg** [comment]
See https://github.com/cymcsg/UltimateRecyclerView/pull/497
