### ISSUE TITLE
when i use it,it cause some questions

### ISSUE THREAD

**Issue by gushoubang** [cymcsg/UltimateRecyclerView#50]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 18
    buildToolsVersion '22.0.1'
    defaultConfig {
        applicationId "test"
        minSdkVersion 15
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
}
repositories {
    mavenCentral()
    //UltimateRecyclerView 用到的
    jcenter()
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:support-v4:22.1.1'
    //网络请求
    compile 'com.loopj.android:android-async-http:1.4.7'
    //加载图片类库
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.3'
    //阿里fastjson
    compile files('libs/fastjson-1.1.43.android.jar')
    //recyclerview
    compile 'com.android.support:recyclerview-v7:22.1.1'
    //viewpager tablayout
    compile 'com.ogaclejapan.smarttablayout:library:1.1.3@aar'
    //圆形图片
    compile 'de.hdodenhof:circleimageview:1.3.0'
    //卡片背景
    compile 'com.android.support:cardview-v7:22.1.1'
    //扇形菜单
    compile 'com.oguzdev:CircularFloatingActionMenu:1.0.2'
    //photoview支持图片放大缩小
    compile 'com.github.chrisbanes.photoview:library:1.2.3'
    //动画库
    compile files('libs/nineoldandroids-2.4.0.jar')
    //gif显示类库
    compile 'pl.droidsonroids.gif:android-gif-drawable:1.1.+'
    compile 'com.marshalchen.ultimaterecyclerview:library:0.3.4'
}

**Comment by gushoubang** [comment]
D:\dituhui_app_android\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\22.0.0\res\values-v11\values.xml
Error:(47, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
Error:(47, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
Error:(47, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
Error:(47, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
D:\dituhui_app_android\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\22.0.0\res\values-v14\values.xml
Error:(17, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
Error:(17, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
Error:(17, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
Error:(17, 21) No resource found that matches the given name: attr 'android:actionModeShareDrawable'.
D:\dituhui_app_android\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\22.0.0\res\values-v21\values.xml
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Body1'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Body2'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Button'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Caption'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display1'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display2'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display3'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display4'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Headline'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Inverse'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Large'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Large.Inverse'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Large'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Small'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Medium'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Medium.Inverse'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Menu'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.SearchResult.Subtitle'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.SearchResult.Title'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Small'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Small.Inverse'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Subhead'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Title'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Menu'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Subtitle'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Subtitle.Inverse'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Title'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Title.Inverse'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionMode.Subtitle'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionMode.Title'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Large'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Small'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Button'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.TextView.SpinnerItem'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Subtitle'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Title'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:ThemeOverlay.Material'.
Error:(79, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(78, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:ThemeOverlay.Material.ActionBar'.
Error:(79, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(78, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:ThemeOverlay.Material.Dark'.
Error:(79, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(78, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:ThemeOverlay.Material.Dark.ActionBar'.
Error:(79, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(78, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:ThemeOverlay.Material.Light'.
Error:(79, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(78, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionBar.TabText'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionBar.TabView'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionButton'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionButton.CloseMode'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionButton.Overflow'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.AutoCompleteTextView'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Small'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.DropDownItem.Spinner'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.ActionBar.TabText'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.ActionBar.TabText'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.ActionBar.TabView'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.PopupMenu'.
Error:(285, 21) No resource found that matches the given name: attr 'android:overlapAnchor'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ListPopupWindow'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ListView.DropDown'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ListView'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.PopupMenu'.
Error:(285, 21) No resource found that matches the given name: attr 'android:overlapAnchor'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ProgressBar'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ProgressBar.Horizontal'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.RatingBar'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner.Underlined'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.TextView.SpinnerItem'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Toolbar.Button.Navigation'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Dialog'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Light'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Light.Dialog'.
Error:(146, 21) No resource found that matches the given name: attr 'android:colorAccent'.
Error:(148, 21) No resource found that matches the given name: attr 'android:colorControlActivated'.
Error:(79, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(78, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(144, 21) No resource found that matches the given name: attr 'android:colorPrimary'.
Error:(145, 21) No resource found that matches the given name: attr 'android:colorPrimaryDark'.
Error:(146, 21) No resource found that matches the given name: attr 'android:colorAccent'.
Error:(148, 21) No resource found that matches the given name: attr 'android:colorControlActivated'.
Error:(79, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(78, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(144, 21) No resource found that matches the given name: attr 'android:colorPrimary'.
Error:(145, 21) No resource found that matches the given name: attr 'android:colorPrimaryDark'.
Error:(146, 21) No resource found that matches the given name: attr 'android:colorAccent'.
Error:(148, 21) No resource found that matches the given name: attr 'android:colorControlActivated'.
Error:(79, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(78, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(144, 21) No resource found that matches the given name: attr 'android:colorPrimary'.
Error:(145, 21) No resource found that matches the given name: attr 'android:colorPrimaryDark'.
Error:(146, 21) No resource found that matches the given name: attr 'android:colorAccent'.
Error:(148, 21) No resource found that matches the given name: attr 'android:colorControlActivated'.
Error:(79, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(78, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(144, 21) No resource found that matches the given name: attr 'android:colorPrimary'.
Error:(145, 21) No resource found that matches the given name: attr 'android:colorPrimaryDark'.
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\Android\ADT\sdk\build-tools\22.0.1\aapt.exe'' finished with non-zero exit value 1

**Comment by gushoubang** [comment]
if i don'use  compile 'com.marshalchen.ultimaterecyclerview:library:0.3.4'
the project is ok

**Comment by cymcsg** [comment]
How about changing ``compileSdkVersion`` to version 22 ?

**Comment by gushoubang** [comment]
New problems arise

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\Android\Java\javamain\bin\java.exe'' finished with non-zero exit value 2

**Comment by cymcsg** [comment]
Maybe you can ``gradle clean`` before build the project.
If it does not take effect,please use google to find some answer like [this](http://stackoverflow.com/questions/28640314/android-studio-fails-to-debug-with-error-org-gradle-process-internal-execexcepti)

**Comment by gushoubang** [comment]
it is some libray is double?

**Comment by cymcsg** [comment]
```groovy
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile 'com.android.support:recyclerview-v7:21.0.3'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'in.srain.cube:ultra-ptr:1.0.9@aar'
    compile 'com.timehop.stickyheadersrecyclerview:library:0.4.0@aar'
```
I think you can remove ``compile files('libs/nineoldandroids-2.4.0.jar')`` this line in your build.gradle

**Comment by gushoubang** [comment]
All the things is OK,thank you very much.
As you said:

Maybe you can gradle clean before build the project.
If it does not take effect,please use google to find some answer like this

and:

    compile 'com.android.support:appcompat-v7:22.0.0'
    compile 'com.android.support:recyclerview-v7:21.0.3'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'in.srain.cube:ultra-ptr:1.0.9@aar'
    compile 'com.timehop.stickyheadersrecyclerview:library:0.4.0@aar'
I think you can remove compile files('libs/nineoldandroids-2.4.0.jar') this line in your build.gradle
