### ISSUE TITLE
setOnLoadMoreListener

### ISSUE THREAD

**Issue by gushoubang** [cymcsg/UltimateRecyclerView#52]
i use it like this,but it doen't work

     rv_mycre.setOnLoadMoreListener(new UltimateRecyclerView.OnLoadMoreListener() {
            @Override
            public void loadMore(int i, int i2) {
               // fg_recommend_presenter.getRcdPost(lasId);
            }
        });

I want know how to use it

**Comment by gushoubang** [comment]
it dont show progress bar

**Comment by cymcsg** [comment]
You should also use ``ultimateRecyclerView.enableLoadmore();`` before ``setOnLoadMoreListener``.

**Comment by gushoubang** [comment]
it is work   ultimateRecyclerView.enableLoadmore();
but it don't show progressbar.I want know how to add progressbar

**Comment by cymcsg** [comment]
You can use ``setCustomLoadMoreView`` to use your custom loading more view.

**Comment by gushoubang** [comment]
Good，all the things is OK, Come on.

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue. @gushoubang
