### ISSUE TITLE
finished with non-zero exit value 1

### ISSUE THREAD

**Issue by JChord** [cymcsg/UltimateRecyclerView#54]
When I ran build task, it's got a error:
ERROR: In <declare-styleable> FloatActionButton, unable to find attribute icon, how can I fix it ?

**Comment by cymcsg** [comment]
Could you show more detail about your problem? Do you use the latest version of the project and use the right configuration?

**Comment by JChord** [comment]
OK, I solved it. It's caused by `appcompat-v7` which I added in exclude group.
`Because Attribute “color” has already been defined`. I must renamed my `declare-styleable`.
