### ISSUE TITLE
can't drag item to the first position

### ISSUE THREAD

**Issue by ksxkq** [cymcsg/UltimateRecyclerView#56]

**Comment by cymcsg** [comment]
The drag method will change for new Recyclerview V22.

**Comment by mori-honest** [comment]
Is This problem fixed?
I have the same problem.

**Comment by cymcsg** [comment]
Do you mean you can not drag to the first item besides the parallaxheader?
You can just try demo and find out if the library has problem.
In my test, it works fine.

**Comment by mori-honest** [comment]
I don't have a parallax header, but the demo does. so maybe i should config it differently?
this is my code: 

    final MorningNightAdapter simpleRecyclerViewAdapter = new MorningNightAdapter(getActivity(), mExtensions);

        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(getActivity());
        ultimateRecyclerView.setLayoutManager(linearLayoutManager);
        ultimateRecyclerView.setAdapter(simpleRecyclerViewAdapter);
        ultimateRecyclerView.enableDefaultSwipeRefresh(false);

        final DragDropTouchListener dragDropTouchListener = new DragDropTouchListener(ultimateRecyclerView.mRecyclerView, getActivity()) {


            @Override
            protected void onItemSwitch(RecyclerView recyclerView, int from, int to) {
                //  if (from >= 0 && to >= 0)
                {
                    simpleRecyclerViewAdapter.swapPositions(from, to);
                }

            }

            @Override
            protected void onItemDrop(RecyclerView recyclerView, int position) {
                simpleRecyclerViewAdapter.notifyDataSetChanged();
            }
        };
        ItemTouchListenerAdapter itemTouchListenerAdapter = new ItemTouchListenerAdapter(ultimateRecyclerView.mRecyclerView,
                new ItemTouchListenerAdapter.RecyclerViewOnItemClickListener() {
                    @Override
                    public void onItemClick(RecyclerView parent, View clickedView, int position) {
                    }

                    @Override
                    public void onItemLongClick(RecyclerView parent, View clickedView, int position) {
                        dragDropTouchListener.startDrag();

                    }
                });
        ultimateRecyclerView.mRecyclerView.addOnItemTouchListener(itemTouchListenerAdapter);
        //  dragDropTouchListener.setCustomDragHighlight(getResources().getDrawable(R.drawable.custom_drag_frame));
        ultimateRecyclerView.mRecyclerView.addOnItemTouchListener(dragDropTouchListener);


My Adapter:


    public class MorningNightAdapter extends UltimateViewAdapter {
    private static final String DELETE_ICON = "\uf057";
    private final Context mContext;
    private List<Extension> mItems;

    public MorningNightAdapter(Context context, List<Extension> mItems) {
        this.mContext = context;
        this.mItems = mItems;
    }


    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int i) {
      //  if (i < getItemCount() && (customHeaderView != null ? i <= mItems.size() : i < mItems.size()) && (customHeaderView == null || i > 0))
        {
            try {
                int position = customHeaderView != null ? i - 1 : i;
                Extension item = mItems.get(position);

                ViewHolder h = (ViewHolder) holder;

                h.textViewIndex.setText(String.valueOf(position + 1));
                if (APP_TYPE_FORWARD.equals(item.type)) {
                    h.extensionTypeTextView.setText(APP_TYPE_FORWARD_ICON);
                    h.extensionInfoTextView.setText(item.config.phoneNumber);
                } else if (APP_TYPE_VOICEMAIL.equals(item.type)) {
                    h.extensionTypeTextView.setText(APP_TYPE_VOICEMAIL_ICON);
                    h.extensionInfoTextView.setText(mContext.getString(R.string.voicemail));
                } else if (APP_TYPE_ANNOUNCEMENT.equals(item.type)) {
                    h.extensionTypeTextView.setText(APP_TYPE_ANNOUNCEMENT_ICON);
                    h.extensionInfoTextView.setText(mContext.getString(R.string.announcement));
                } else if (APP_TYPE_RECEIVE_FAX.equals(item.type)) {
                    h.extensionTypeTextView.setText(APP_TYPE_FAX_ICON);
                    h.extensionInfoTextView.setText(mContext.getString(R.string.fax));
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }

    @Override
    public int getAdapterItemCount() {
        return mItems.size();
    }

    @Override
    public UltimateRecyclerviewViewHolder onCreateViewHolder(ViewGroup parent) {
        View v = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.row_morning_night, parent, false);
        return new ViewHolder(v);
    }


    public void insert(Extension extension, int position) {
        insert(mItems, extension, position);
    }

    public void remove(int position) {
        remove(mItems, position);
    }

    public void clear() {
        clear(mItems);
    }

    @Override
    public void toggleSelection(int pos) {
        super.toggleSelection(pos);
    }

    @Override
    public void setSelected(int pos) {
        super.setSelected(pos);
    }

    @Override
    public long generateHeaderId(int i) {
        return 0;
    }

    @Override
    public void clearSelection(int pos) {
        super.clearSelection(pos);
    }


    public void swapPositions(int from, int to) {
        swapPositions(mItems, from, to);
    }

    @Override
    public RecyclerView.ViewHolder onCreateHeaderViewHolder(ViewGroup viewGroup) {
        return null;
    }

    @Override
    public void onBindHeaderViewHolder(RecyclerView.ViewHolder viewHolder, int i) {

    }


    class ViewHolder extends UltimateRecyclerviewViewHolder {

        TextView textViewIndex;
        TextView extensionTypeTextView;
        TextView extensionInfoTextView;
        LinearLayout innerLinearLayout;

        public ViewHolder(View itemView) {
            super(itemView);
            textViewIndex = (TextView) itemView.findViewById(R.id.indexTextView);
            extensionTypeTextView = (TextView) itemView.findViewById(R.id.extensionTypeTextView);
            extensionInfoTextView = (TextView) itemView.findViewById(R.id.extensionInfoTextView);
            innerLinearLayout = (LinearLayout) itemView.findViewById(R.id.innerItemLinearLayout);
        }
    }

    public Extension getItem(int position) {
        if (customHeaderView != null)
            position--;
        if (position < mItems.size())
            return mItems.get(position);
        else return new Extension();
    }

}

**Comment by mori-honest** [comment]
Any solution?

**Comment by mori-honest** [comment]
I added a header view and the problem was gone. but i don't want a header view!
How to fix this?

**Comment by cymcsg** [comment]
Have you tried the demo code which just remove ``ultimateRecyclerView.setParallaxHeader`` and ``ultimateRecyclerView.setOnParallaxScroll`` . Then the demo does not have header and it works find.

**Comment by mori-honest** [comment]
Ofcourse!
Have you looked at my code above?
it does not have any parallax header!

**Comment by cymcsg** [comment]
I mean you can ``REMOVE`` the ``ultimateRecyclerView.setParallaxHeader`` and ``ultimateRecyclerView.setOnParallaxScroll`` in demo so the demo ``DO NOT HAVE`` header any more.

**Comment by mori-honest** [comment]
I don't have any `setParallaxHeader` or `setOnParallaxScroll ` and still having problem.
This is my code:

     LinearLayoutManager linearLayoutManager = new LinearLayoutManager(getActivity());
    ultimateRecyclerView.setLayoutManager(linearLayoutManager);
    ultimateRecyclerView.setAdapter(simpleRecyclerViewAdapter);
    ultimateRecyclerView.enableDefaultSwipeRefresh(false);

    final DragDropTouchListener dragDropTouchListener = new DragDropTouchListener(ultimateRecyclerView.mRecyclerView, getActivity()) {


        @Override
        protected void onItemSwitch(RecyclerView recyclerView, int from, int to) {
            //  if (from >= 0 && to >= 0)
            {
                simpleRecyclerViewAdapter.swapPositions(from, to);
            }

        }

        @Override
        protected void onItemDrop(RecyclerView recyclerView, int position) {
            simpleRecyclerViewAdapter.notifyDataSetChanged();
        }
    };
    ItemTouchListenerAdapter itemTouchListenerAdapter = new ItemTouchListenerAdapter(ultimateRecyclerView.mRecyclerView,
            new ItemTouchListenerAdapter.RecyclerViewOnItemClickListener() {
                @Override
                public void onItemClick(RecyclerView parent, View clickedView, int position) {
                }

                @Override
                public void onItemLongClick(RecyclerView parent, View clickedView, int position) {
                    dragDropTouchListener.startDrag();

                }
            });
    ultimateRecyclerView.mRecyclerView.addOnItemTouchListener(itemTouchListenerAdapter);
    //  dragDropTouchListener.setCustomDragHighlight(getResources().getDrawable(R.drawable.custom_drag_frame));
    ultimateRecyclerView.mRecyclerView.addOnItemTouchListener(dragDropTouchListener);

**Comment by cymcsg** [comment]
The drag method has been changed in the latest version of UltimateRecyclerview 0.3.9.
You can try it out.
Thank you.
