### ISSUE TITLE
how can i add a default or custom divider?

### ISSUE THREAD

**Issue by mori-honest** [cymcsg/UltimateRecyclerView#58]

**Comment by cymcsg** [comment]
`` ultimateRecyclerView.addItemDecoration(
                new HorizontalDividerItemDecoration.Builder(this).build());``
You can use addItemDecoration like this.

**Comment by mori-honest** [comment]
thanks,...and how to customize it?

**Comment by cymcsg** [comment]
You can add your custom DividerItemDecoration.

**Comment by mori-honest** [comment]
1. I added divider but first item after each sticky header does not have a divider at top.
how can i add that too?
![untitled](https://cloud.githubusercontent.com/assets/5219339/8270736/3fecea3a-1805-11e5-9cef-504f3889d5cf.jpg)

**Comment by cymcsg** [comment]
Do you think it will help you if you add a line in your custom sticky header?

**Comment by mori-honest** [comment]
I tried it! but notice that the line sticks to the header instead of the first item's top when scrolling down and it is ugly!

**Comment by cymcsg** [comment]
Yes,it's ugly.
However add a line under sticky header is some kind strange for a item of recylcerview. I'll tried to find a way to enhance it.It's very grateful if you have some great ideas .
