### ISSUE TITLE
Where is disableLoadMore?

### ISSUE THREAD

**Issue by parkjaeiek** [cymcsg/UltimateRecyclerView#6]
where is disableLoadMore?

i want stop loadMore

**Comment by cymcsg** [comment]
The ``LoadMore`` method is disable in default. So if you don't want to use loading more you can simply remove ``enableLoadmore()`` method in demo.

You can remove these code in demo.
```java
   ultimateRecyclerView.enableLoadmore();
   simpleRecyclerViewAdapter.setCustomLoadMoreView(LayoutInflater.from(this)
                .inflate(R.layout.custom_bottom_progressbar, null));
```

**Comment by parkjaeiek** [comment]
i know disable default....
my probleam mean... 
i need enableLoadMore.... 
example 10 totalitem
call 1page 3item... loadmore 4 call after disableLoadMore need....
last page do not call loadmore

**Comment by cymcsg** [comment]
Thank you for giving this advice.
In fact ,the current released version do not have the method of ``disableLoadmore()``.But in the latest dev version it has been improved.
Please notice that the method has some side effects if you also use parallax head view in the same time.

**Comment by cymcsg** [comment]
Now you can use Ultimate Recyclerview version 0.3.1 to solve the problem.
