### ISSUE TITLE
How can i add a custom swipe layout like this?

### ISSUE THREAD

**Issue by mori-honest** [cymcsg/UltimateRecyclerView#60]
How to set a swipe layout to list like this:
![screen shot 1394-03-12 at 14 05 29](https://cloud.githubusercontent.com/assets/5219339/7932911/b519db3a-0930-11e5-80a0-6c817a31040e.png)

**Comment by cymcsg** [comment]
Do you mean you want a feature which you can click the details after you swipe?
In current version,the UltimateRecyclerview only support ``Swipe to Dismiss``.I think it is a good idea to add feature like this in the future.

**Comment by mori-honest** [comment]
in one of screenshots there is something like this in it...
![screenshot](https://camo.githubusercontent.com/ef7c10223b6b1c33acff00c20c236df798c25cc9/68747470733a2f2f627974656275636b65742e6f72672f6d61727368616c6368656e2f696d616765732f7261772f663437393439373464386465373161623164306630656664646461353536646637653739326466322f756c74696d61746572656379636c6572766965772f756c74696d6174655f72656379636c657276696577332e676966)

**Comment by cymcsg** [comment]
@mori-honest Yes,but it can not swipe to some other position you define now.

**Comment by mori-honest** [comment]
How can i implement that screenshot?
there is nothing in wiki...

**Comment by cymcsg** [comment]
@mori-honest  You can read the demo [here](https://github.com/cymcsg/UltimateRecyclerView/blob/bfeffc3933912322d0f98248415cd3c8e9862bb8/UltimateRecyclerView/app/src/main/java/com/marshalchen/ultimaterecyclerview/demo/SwipeBottomActivity.java)

**Comment by mori-honest** [comment]
You can use include this lib in yours:
https://github.com/baoyongzhang/SwipeMenuListView

**Comment by cymcsg** [comment]
In the current version of UltimateRecyclerview,there is a swipe-hold activity.You can try it out.

**Comment by mori-honest** [comment]
Can you please give me the link?
i can't find it

**Comment by cymcsg** [comment]
You can simply find it in Demo's menu

**Comment by mori-honest** [comment]
Sorry, but i can't find it... :(

**Comment by cymcsg** [comment]
Update to the latest version,and there is a swipe and drag activity.
Do you think that meets your need?

**Comment by mori-honest** [comment]
I'm at version 1.0.6, and i can't find it....

**Comment by cymcsg** [comment]
@mori-honest  I think you can use the ``latest`` version of demo. Do you use the version on GooglePlay？It's not the latest version.You can download the source code and run ``gradle build`` to generate it.

**Comment by mori-honest** [comment]
yes... thank you.

**Comment by mori-honest** [comment]
I created the swipe layout but there is another problem here: https://github.com/cymcsg/UltimateRecyclerView/issues/84

**Comment by mori-honest** [comment]
And if you can add swipe:swipeOffsetRight too, it would be great!
thanx

**Comment by cymcsg** [comment]
You can customize the offset the widget hangs.Do you mean that feature or the offset that causes swipe method?

**Comment by mori-honest** [comment]
sorry! I should have created a new issue.
I mean if there was a new attribute that could set swipe hang offset from right(instead of offset from left), it would be great. 
![screen shot 1394-04-01 at 10 02 29](https://cloud.githubusercontent.com/assets/5219339/8276021/e218ce6c-18c5-11e5-9e3a-e4a28a330968.png)

**Comment by Rainer-Lang** [comment]
@mori-honest Have you tried this? https://github.com/daimajia/AndroidSwipeLayout

**Comment by cymcsg** [comment]
The latest version has included that layout

**Comment by Rainer-Lang** [comment]
Great. :-) 

But there is still the problem (other issue) with the viewpager....
