### ISSUE TITLE
Load more View not shown

### ISSUE THREAD

**Issue by ImranAtArbisoft** [cymcsg/UltimateRecyclerView#63]
I have downloaded latest code and run. Load more view is shown and working fine in `MainActivity` ( https://github.com/cymcsg/UltimateRecyclerView/blob/master/UltimateRecyclerView/app/src/main/java/com/marshalchen/ultimaterecyclerview/demo/MainActivity.java )
But in `MultiViewTypesActivity ` ( https://github.com/cymcsg/UltimateRecyclerView/blob/master/UltimateRecyclerView/app/src/main/java/com/marshalchen/ultimaterecyclerview/demo/MultiViewTypesActivity.java ) it is not shown.
`loadMore` is called, but load more view does not appear.
i just added below lines:
 ultimateRecyclerView.enableLoadmore();
        ultimateRecyclerView.setOnLoadMoreListener(new UltimateRecyclerView.OnLoadMoreListener() {
            @Override
            public void loadMore(int itemsCount, int maxLastVisiblePosition) {
                Log.d(">>Test>>","onLoadMOre");
            }
        });

If there is issue in code, please fix it or guide me how to fix. 

Regards

**Comment by cymcsg** [comment]
In the current version,the MultiViewTypes adapter does not support loading more feature.I'll try to add this feature in the future.

**Comment by ImranAtArbisoft** [comment]
Thanks for reply.
I am currently very bad situation of my project. i need this feature .
Can u guide me where i have to implement this feature in your code, so that i can implement.

Thanks

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue. @ImranAtArbisoft if you have the adapter based on ultimate adapter then this should be fine!

**Comment by mohammadaminha** [comment]
Hi,Thanks for this amazing library
i have the same issue to ! 
but its not working on first load more scrolling ! 
second time its working curectly
i add the load more view to recycler and adapter ! 
ultimateRecyclerView.setLoadMoreView(R.layout.load_more_view);
ultimateViewAdapter.setCustomLoadMoreView(loadmoreView);
but as i say
its not working on first load more scroll
