### ISSUE TITLE
CustomLoadMoreView cannot be hidden

### ISSUE THREAD

**Issue by fsoeltoni** [cymcsg/UltimateRecyclerView#64]
I can't hide load more progress bar after it finished loading... i also put setVisible(View.gone) but it didn't happened... any help always be appreciated... thanx

**Comment by jjhesk** [comment]
There should be a few different solutions
- [ ] remove the loadmore view manually when the data is done loading the first time. (only when there is no pagination implemented from the api or not intended to implement pagination in listview)
- [ ] replace with the a "LOAD MORE" button and do not more trigger load more function automatically.

**Comment by fsoeltoni** [comment]
I've solved it thank you jjhesk

**Comment by LeeeYou** [comment]
@fsoeltoni  how do you solved it by @jjhesk 's solutions
