### ISSUE TITLE
Feature request: JazzyHelper

### ISSUE THREAD

**Issue by jjhesk** [cymcsg/UltimateRecyclerView#67]
Yes, we need this.
I have came across this library before and I used that one because it has the collection of the nice effects. Have you start pushing these code in it? Otherwise I can start working on it. [JazzListView](https://github.com/twotoasters/JazzyListView) and I can start from [here](https://github.com/jjhesk/JazzyListView/blob/master/library/src/main/java/com/twotoasters/jazzylistview/JazzyHelper.java)

**Comment by jjhesk** [comment]
I want to know which one is better compared to the existing [animators](https://github.com/cymcsg/UltimateRecyclerView/tree/master/UltimateRecyclerView/ultimaterecyclerview/src/main/java/com/marshalchen/ultimaterecyclerview/animators)

**Comment by cymcsg** [comment]
I also think it has many amazing effects and I think it can be combined with the existing animators.
I hope you could work on it.

**Comment by jjhesk** [comment]
I need sometime to study it. Recently I came cross the admob and it has some bad effects when its loaded and ported into the view. It starts blinking and i know why. I hope this effect solution can smooth out the bad effects from loading admob adviews. By the way, @cymcsg  do you know any tricks to make the banner on the list recycleview to be full width?? Let me know if u got some hacks.
