### ISSUE TITLE
[ProgressBar] Load more not showing

### ISSUE THREAD

**Issue by HildonEduardo** [cymcsg/UltimateRecyclerView#7]
HI, Im trying to use enabledMore feature, but when I scroll down, progress bar not showing, can you explain me how this works, and if there is some callback like onRefresh (pull from top) to loadmore... I was thinking in populate recycler from a paginated get service...

Thanks,

**Comment by cymcsg** [comment]
Thank you.
Do you try to use `` ultimateRecyclerView.enableLoadmore()``? 
If you want to some other load more view you can use ``simpleRecyclerViewAdapter.setCustomLoadMoreView(LayoutInflater.from(this)
                .inflate(R.layout.custom_bottom_progressbar, null));`` .I think you can see the demo code if you want to use some feature.Or if you still get some problem,you can show your code.

**Comment by HildonEduardo** [comment]
Yes, I tried, here is the code:

@Override
    public View onCreateView(final LayoutInflater inflater, final ViewGroup container,
                             final Bundle savedInstanceState) {

        final View mainView = inflater.inflate(R.layout.fragment_gallery, container, false);

        recyclerGallery = (UltimateRecyclerView) mainView.findViewById(R.id.gallery_recycler_view);
        gridManager = new GridLayoutManager(getActivity(), 3);
        recyclerGallery.setLayoutManager(gridManager);


        return mainView;
    }

    private List<GalleryItem> populateFakeGallery(final int quantity) {
        final List<GalleryItem> items = new ArrayList<>();

        for (int i = 0; i < quantity; i++) {
            final GalleryItem galleryItem = new GalleryItem();
            galleryItem.setImgThumbUrl("http://www.icon100.com/up/2841/256/dota2.png");
            galleryItem.setAuthor("Valve.");
            galleryItem.setItemId(String.valueOf(i));
            items.add(galleryItem);
        }

        return items;
    }

    @Override
    public void onViewCreated(final View view, final Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        adapter.setFragment(this);
        items = populateFakeGallery(15);
        adapter.setGalleryItems(items);
        recyclerGallery.setAdapter(adapter);
        recyclerGallery.enableLoadmore();
        recyclerGallery.setOnRefreshListener(this);
        recyclerGallery.setVerticalScrollBarEnabled(true);
        recyclerGallery.setOnLoadMoreListener(new UltimateRecyclerView.OnLoadMoreListener() {
            @Override
            public void loadMore(int i, int i2) {
                items.addAll(populateFakeGallery(15));
                adapter.setGalleryItems(items);
                Toast.makeText(getActivity(), "page[" + pageCounter + "] Loading 15 more...", Toast.LENGTH_SHORT).show();
                pageCounter++;
                gridManager.scrollToPosition(i2);
            }
        });

        adapter.setCustomLoadMoreView(LayoutInflater.from(getActivity())
                .inflate(R.layout.custom_bottom_progressbar, null));
    }


I followed the demo,

Thanks

**Comment by cymcsg** [comment]
I have tried some code like you and  changed ``LinearLayoutManager`` to ``GridLayoutManager`` in the demo and  everything works fine.I wonder if you mean you can not see the progress bar or the progress bar do not take effect.

**Comment by gouravd** [comment]
The callback for LoadMore gets called properly, but the LoadMore custom view is not visible for me too. I am using LinearLayoutManager

**Comment by cymcsg** [comment]
In fact the ``OnLoadMoreListener `` method also use the ``RecyclerView.OnScrollListener()``.So if you want to use custom ScrollListener you should implement the loading more yourself in current version.

I'll try to let it more convenient to use and I hope to listen your good advice.

**Comment by Wolftein** [comment]
What about moving the LoadMore view from the adapter into the recycler view?, i'm using UltimateRecyclerView with another adapter library that fits my need and to have load more i need to use UltimateRecyclerViewAdapter which i don't want to.

**Comment by cymcsg** [comment]
@Wolftein Thank you for you advice.In fact the UltimateRecyclerViewAdapter has many feature rather than just the loading more view.So I do not think it's a good idea to do just that.
Could I ask your which library do you use? Maybe I can try to find a good way to combine them.

**Comment by Wolftein** [comment]
@cymcsg , I'm currently using https://github.com/StanKocken/EfficientAdapter for the adapter combined with UltimateRecyclerView

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.
