### ISSUE TITLE
Load More layout hides when swipe to refresh from top.

### ISSUE THREAD

**Issue by mori-honest** [cymcsg/UltimateRecyclerView#73]
Load more layout is shown and loads and hides successfully but when i try to refresh list with swipe, and then go to the end of the list, "load more layout disappears", but loadmore function works fine.
i think the problem is that you assign load more layout as last item of the list and when i try to delete the list and load new ones it is removed. am i right?
what is the correct way to fix this?

**Comment by mori-honest** [comment]
I found the problem!
When i reach end of the list and there is no other item in the database, i call 

    mRecyclerView.disableLoadmore();

and from this on, any call to 

    mRecyclerView.enableLoadmore();
        mAdapter.setCustomLoadMoreView(LayoutInflater.from(getActivity())
                .inflate(R.layout.progressbar_bottom_load_more_recycler_view, null));

is not inflating load more layout.
what is wrong here?

**Comment by cymcsg** [comment]
This problem is caused by the method ``disableLoadmore``. There are some bugs when you call the method more than once.I'll try to fix it in the future. #71 also said that.

**Comment by mori-honest** [comment]
Is this fixed in version 0.3.5?

**Comment by cymcsg** [comment]
@mori-honest  Sorry,it has not solved yet.

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue. @mori-honest

**Comment by mori-honest** [comment]
Is this issue fixed or just closed?

**Comment by reancool** [comment]
I it takes me a lot of time ,but bug sitll have .loadmore can't hide
