### ISSUE TITLE
Please remove ic_launcher.png

### ISSUE THREAD

**Issue by muratogat** [cymcsg/UltimateRecyclerView#75]
The latest gradle plugin 1.2.3 does not allow resources with the same name. Even when the icon of the project is renamed to something else, ic_launcher.png can conflict with the same file from other libraries, which still didn't remove it like this one. This forces me to downgrade to gradle plugin 1.1.3.

Please remove the unnecessary file.

**Comment by cymcsg** [comment]
In the latest version on dev branch,there is no ic_launcher.png left.

**Comment by cymcsg** [comment]
Now you can try the latest 0.3.5 version
