### ISSUE TITLE
implementing the new observable view

### ISSUE THREAD

**Issue by jjhesk** [cymcsg/UltimateRecyclerView#76]
the library is coming from [the ob](https://github.com/ksoichiro/Android-ObservableScrollView) . I am working on how to get this working on the existing lib. There are much work needed. I am trying to implement viewpager + header as slider + list view use ultimate recyclerview. I think this should be an add on to the current lib. This also solved the problem from #45

**Comment by cymcsg** [comment]
I also think it's awesome to implement these features.

**Comment by jjhesk** [comment]
@cymcsg will you do any updates in the next 12 hours? cause i am trying to pull

**Comment by cymcsg** [comment]
Go ahead.Hoping for your enhancement.

**Comment by jjhesk** [comment]
@cymcsg  it is finally working now =)))) CHEERS!! it was a big hack!!

**Comment by cymcsg** [comment]
That's awesome! I have merged it into dev.But do you think it is a better idea to enhance the demo of  ``ScrollObservablesActivity`` or MainActivity? I can hardly see much of the new feature in the ``ScrollObservablesActivity``.That's very kind of you.

**Comment by jjhesk** [comment]
I have added and use viewpager on the bottom part. it takes extra mechanism to calculate the top moving part. I will come up with a better demo the next pull and because i am still working on the next pull. i will have another pull soon and this will not change any of your code. U can wait for me before you do any PR.. thank you.
