### ISSUE TITLE
Library Compatibility

### ISSUE THREAD

**Issue by marbat87** [cymcsg/UltimateRecyclerView#8]
It seems that the library is compatible with API 11 or higher only (because of many animations)
On Android Arsenal is written "API 7".

**Comment by cymcsg** [comment]
Now the library is  compatible with API 11 as it has been add more effects.
It is compatible with API 7 at first.But in fact you can also use it in API 7 if you do not need all the effect in UltimateRecyclerview

**Comment by marbat87** [comment]
So, If I use this library, does it work on API 7 without animations, as is? Or should I edit it manually in order to make it working?

**Comment by marbat87** [comment]
It doesn't allow me to include the library, if minSdk is lower than 12...

**Comment by cymcsg** [comment]
In the current version,you need to import the source code into the project and use it if you want to use with API 7.
