### ISSUE TITLE
direct or indirect cause for exceptions.

### ISSUE THREAD

**Issue by jjhesk** [cymcsg/UltimateRecyclerView#80]
I have tested many times and it always show this after open and close the app.
It happens when the app closed and reopen it again after a while. 

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$LayoutManager.canScrollVertically()' on a null object reference

I enabled to the loadmore and pull to refresh gestures.

**Comment by cymcsg** [comment]
Do you think it is possible due to [this](http://stackoverflow.com/questions/27416834/app-crashing-when-trying-to-use-recyclerview-on-android-5-0)?

**Comment by jjhesk** [comment]
@cymcsg +1 brilliant. It is related to this.

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.
