### ISSUE TITLE
Is it possible to show progress bar before setting an adapter ?

### ISSUE THREAD

**Issue by R4md4c** [cymcsg/UltimateRecyclerView#86]
Is it possible to show a circular progress bar that keeps animating at the center of the widget until an adapter is set  ? 

Something like  showProgress.and hideProgress

**Comment by cymcsg** [comment]
There is an empty view which can be shown before setting an adapter.

**Comment by R4md4c** [comment]
But what if I have already data in the adapter, and I need to show an empty view for reloading ? I don't see any "showEmptyView" method in UltimateRecyclerView.

**Comment by ivazhnov** [comment]
same question. I'm starting reloading data, i wanna hide current data and show placeholder and refreshing widget. But when i clear my adapter data placeholder shows, but it also hides refreshing widget...

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue. @ivazhnov @R4md4c
