### ISSUE TITLE
Empty view won't show when adapter item count is zero.

### ISSUE THREAD

**Issue by mori-honest** [cymcsg/UltimateRecyclerView#88]
I set the attribute:

     swipe:recyclerviewEmptyView="@layout/tour_main_overview"

and the item count is zero but the empty layout flashes for a second and disappears.

**Comment by cymcsg** [comment]
Have you tried the demo and set a zero count adapter to the recyclerview? I tried and it works fine.

**Comment by mori-honest** [comment]
Can you please give me the link of that class?
i can't find it...

**Comment by cymcsg** [comment]
The MainActivity in demo.You can remove ``ultimateRecyclerView.enableLoadmore();`` and make stringList as a empty list in that class.

**Comment by mori-honest** [comment]
...But I want enableLoadmore() method somewhere in my code...

**Comment by cymcsg** [comment]
You can enableLoadmore. But in demo,the loading more feature will load data to the adapter so the adapter is not null any more.

**Comment by mori-honest** [comment]
I'm confused!
Please add a snippet that shows how to do this that can work.
thank you.

**Comment by cymcsg** [comment]
Do you insert some items into the adapter when loading more?If you do that the adapter is not empty after loading more.

**Comment by mori-honest** [comment]
I'm inserting items after loading more but the problem is that before this, i can't see emptyView.

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue. @mori-honest
