### ISSUE TITLE
Please add these methods to recyclerView

### ISSUE THREAD

**Issue by mori-honest** [cymcsg/UltimateRecyclerView#89]
I want to set empty layout programmatically, but setEmptyLayout and setErrorLayout and setLoadingLayout are missing in your great library.

**Comment by cymcsg** [comment]
In current version,you can set empty layout via xml.I'll try to add programmable method in the future.

**Comment by mori-honest** [comment]
Yes! missing this feature makes me create 8 layouts instead of just one!

**Comment by cymcsg** [comment]
Now,you can use setEmptyView,showEmptyView,hideEmpty in the latest dev version.

**Comment by mori-honest** [comment]
Great!
tanx
