### ISSUE TITLE
EmptyView problem

### ISSUE THREAD

**Issue by Swisyn** [cymcsg/UltimateRecyclerView#9]
I'm fetching files from a folder to recyclerview if the folder doesn't contain any files then i'd like to show empty view. Emptyview is shown if the adapter is set to null right? but when i try to  ultimateRecyclerView.setAdapter(null); it crashes. 

Is there a solution to show empty view when adapter is set null or it can be empty by default?

**Comment by cymcsg** [comment]
Thank you for telling this bug.
In fact the empty view can only show when the  adapter is empty but not null now.
I'll fix the problem today and push the latest version to the dev branch.

**Comment by Swisyn** [comment]
Thank you so much for the quick response.

**Comment by Rainer-Lang** [comment]
Thanks, I also need this.

**Comment by cymcsg** [comment]
The function in  current dev version of the UltimateRecyclerview is fine.
As I am dealing with the [UltimateAndroid](https://github.com/cymcsg/UltimateAndroid)  framework these weeks, so it may take some time to test and publish the released version.
