### ISSUE TITLE
Expandable groups

### ISSUE THREAD

**Issue by sergeyfitis** [cymcsg/UltimateRecyclerView#90]
Hi. Can you add new feature to your UltimateRecyclerView? Expanding groups like in ExpandableListView.

**Comment by Rainer-Lang** [comment]
Wow - this would be pretty nice!

**Comment by sergeyfitis** [comment]
So, you will add this feature?

**Comment by Rainer-Lang** [comment]
I think the idea is nice.

**Comment by sergeyfitis** [comment]
Great, I'll be waiting an update :)

**Comment by jjhesk** [comment]
@cymcsg please flag this as Feature request.

**Comment by sergeyfitis** [comment]
> @cymcsg please flag this as Feature request. It is very hard to incorporate the expandable group into the list group. Can you suggest some existing libraries for reference?

In this library implemented expandable groups [Advanced RecyclerView](https://github.com/h6ah4i/android-advancedrecyclerview) .  

Also my suggestion for an implementation: You can use in the adapter methods ```notifyItemRangeRemoved(groupPosition, range);```
```notifyItemRangeInserted(groupPosition, range);```
to emulate expand and collapse groups.

**Comment by jjhesk** [comment]
@sergeyfitis I just looked at the library and its demo. They have done amazingly perfect alone. It has alot of features which is already overlaped on the existing library. We need to sort out the existing bugs from the current library firsts since it may trigger even more bugs from the integration.

**Comment by Rainer-Lang** [comment]
please also look here: https://github.com/bignerdranch/expandable-recycler-view

**Comment by jjhesk** [comment]
@Rainer-Lang @sergeyfitis @cymcsg this seems to done at this point and it allows plenty of external customisations along with this LinearExpanxURVAdapter. 

Dont forget to give me credits. Cheers!!

**Comment by cymcsg** [comment]
@jjhesk Awesome!

**Comment by Rainer-Lang** [comment]
@jjhesk Wow - that's really great!!!! Thanks.

**Comment by jjhesk** [comment]
@cymcsg 
please also set this into the milestone for v0.4.0
