### ISSUE TITLE
demo app hide toolbar while quickly swipping down after enter app

### ISSUE THREAD

**Issue by yanlusu** [cymcsg/UltimateRecyclerView#91]
1. open demo app;
2. in main ui, swipe down faster as faster using finger;
3. toolbar hided.
btw: just first time swipping down quickly after enter app, this problem appeared.

**Comment by cymcsg** [comment]
There is a method `` ultimateRecyclerView.hideToolbar(toolbar, ultimateRecyclerView, getScreenHeight());
`` called in demo
