### ISSUE TITLE
DragSort Adapter for UltimateRecyclerView

### ISSUE THREAD

**Issue by leapfrog-santosh** [cymcsg/UltimateRecyclerView#93]
So far `DragSortAdapter` or drag implements works only on `support v7 recyclerview`. Using it on `UltimateRecyclerView` , it doesn't work at all. Rather than to term it as an issue, need some hint on implementation of drag and drop on `UltimateRecyclerView`. Lastly, awesome library, saves ton of time and keep up the great work.

**Comment by cymcsg** [comment]
In current version you can use ``DragDropTouchListener`` instead of DragSortAdapter to achieve the drag function.You can try it in demo.

**Comment by leapfrog-santosh** [comment]
@cymcsg :+1:  Thanks. I will give it a try.
