### ISSUE TITLE
Please help me with loadmore .I am using volley

### ISSUE THREAD

**Issue by raviteja83** [cymcsg/UltimateRecyclerView#96]
Do we have to give the progessbar view or by default it will display the progress bar? I could not see progressbar.

**Comment by cymcsg** [comment]
You can use `` ultimateRecyclerView.enableLoadmore();`` to add default progress bar .
You can also use ``
        simpleRecyclerViewAdapter.setCustomLoadMoreView(LayoutInflater.from(this)
                .inflate(R.layout.custom_bottom_progressbar, null));``  to customize your view.

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue.  @raviteja83
