### ISSUE TITLE
demo app hide toolbar while quickly swipping down after enter app(with code)

### ISSUE THREAD

**Issue by yanlusu** [cymcsg/UltimateRecyclerView#97]
in UltimateRecyclerView.java, Method: enableShoworHideToolbarAndFloatingButton
    
                    mCallbacks.onScrollChanged(mScrollY, mFirstScroll, mDragging);
                    if (mFirstScroll) {
                        mFirstScroll = false;
                    }
                    if (mPrevScrollY < mScrollY) {
                        //down
                        mObservableScrollState = ObservableScrollState.UP;
                    } else if (mScrollY < mPrevScrollY) {
                        //up
                        mObservableScrollState = ObservableScrollState.DOWN;
                    } else {
                        mObservableScrollState = ObservableScrollState.STOP;
                    }

if first time flipping quickly down(finger's swipping direction is down and quick),  mFristScroll == false, and  mPrevScrollY==0,  mScrollY > 0, so mPrevScrollY < mScrollY, then mObservableScrollState = UP, but in  reality, mObservableScrollState should be DOWN, just becase initially mPrevScrollY==0, so I think the code here should be:
    
                    if (mPrevScrollY < mScrollY) { 
                        //down
                        if (mFirstScroll) { // first scroll down , mPrevScrollY == 0, reach here.
                            mFirstScroll = false;
                            mObservableScrollState = ObservableScrollState.STOP;
                            break;
                        }
                        mObservableScrollState = ObservableScrollState.UP;
                    } else if (mScrollY < mPrevScrollY) {
                        //up
                        mObservableScrollState = ObservableScrollState.DOWN;
                    } else {
                        mObservableScrollState = ObservableScrollState.STOP;
                    }
                    if (mFirstScroll) {
                        mFirstScroll = false;
                    }

**Comment by cymcsg** [comment]
Why do you think it is a problem ?
The toolbar should be hiden if I swipe down when I enable toolbar hide method.

**Comment by yanlusu** [comment]
when finger's flipping direction is up(view's scrolling direction is UP), toolbar hidding is ok.
but the problem is just only the first time, and quickly swiping down your finger(not swiping up), toolbar hidding. is it a problem?
in the normal, when I flling my finger down(the view's scrolling direction is DOWN), the toolbar should be showing.

简单来说，第一次进入app的时候，如果快速手指下滑，toolbar是被隐藏了。
正常情况下，手指上滑，界面向下滚动，这时候toolbar才会隐藏；当toolbar隐藏后，手指下滑，toolbar应该显示出来。
但是demo中第一次进入时，手指下滑，却是隐藏了toolbar，难道这是正常的？

**Comment by yanlusu** [comment]
请关注：我提到的是，手指向下快速滑动（界面应该是向上滚动到顶部），正常情况下手指下滑，toolbar应该是从隐藏状态变成显示状态。
可能是我英语表达不太好，或者是我理解的有问题？

**Comment by cymcsg** [comment]
Sorry for misunderstanding your report.
Thank you very much for telling us such useful bug reporting.I'll check and fix it ASAP.
If you like,you can make a PR.

**Comment by cymcsg** [comment]
As you have not given me a PR, I have used your code in the latest library.
Thank you very much!
