### ISSUE TITLE
disableLoadmore() crash

### ISSUE THREAD

**Issue by anupsarode** [cymcsg/UltimateRecyclerView#99]
Hello,

I initilaize the recyclerview and enable loadmore functionality. Then I make a REST call to get some data. On getting the data, I call disableLoadMore().

When I am calling disableLoadmore(), I get the following error.

```
FATAL EXCEPTION: main java.lang.NullPointerException at 
com.marshalchen.ultimaterecyclerview.UltimateRecyclerView.disableLoadmore(UltimateRecyclerView.java:353)
```

**Comment by jjhesk** [comment]
@cymcsg , let me know if im right. I think the part of the algorithm is that loadmore layout will be removed when the new item is inserted into the list and the notifiedInsertItem is triggered. In result, there is no need to call disableLoadmore().

**Comment by anupsarode** [comment]
On getting the data, I check total number of items give by server. If all the items given by server are added to the Recycler View, I don't need to have the load more functionality even if user scrolls the list upwards. So I'm trying to disable the load more functionality when not needed.

**Comment by drugsweet** [comment]
I also meet the same question.can you solved the problem?

**Comment by cymcsg** [comment]
@anupsarode  @drugsweet  Have you tried the latest version of URV ? You can use  ``disableLoadmore``  and ``reenableLoadmore`` method.

**Comment by drugsweet** [comment]
I tried the lastest version of URV.In demo of URV ,I test! But , no effects!  the code:

ultimateRecyclerView.setOnLoadMoreListener(new UltimateRecyclerView.OnLoadMoreListener() {
            @Override
            public void loadMore(int itemsCount, final int maxLastVisiblePosition) {
                Handler handler = new Handler();
                handler.postDelayed(new Runnable() {
                    public void run() {
                        ultimateRecyclerView.enableLoadmore();
//                        ultimateRecyclerView.reenableLoadmore();
                        Log.e("setOnLoadMoreListener","!!!!!!!!!!!!!!!!!!");
//                        SampleDataboxset.insertMore(simpleRecyclerViewAdapter, 10);
//                          linearLayoutManager.scrollToPositionWithOffset(maxLastVisiblePosition, -1);
//                          linearLayoutManager.scrollToPosition(maxLastVisiblePosition);
                    }
                }, 2500);
            }
        });

**Comment by cymcsg** [comment]
Do you mean you will get a ``NullPointerException`` error or `` I'm trying to disable the load more functionality when not needed`` but it does not take effect?

**Comment by drugsweet** [comment]
@cymcsg  I'm trying to disable the load more functionality when not needed ,but it does not take effect,the progress bar still exists. I think whether I neglect some details. Can you give me a demo about the "disable the load more"? My email :396995798@qq.com.           Thanks!

**Comment by anupsarode** [comment]
@cymcsg - For me, the app doesn't crash now. The NullPointerException is gone. But there's another issue. When the disableLoadMore() is called, my custom loading progress bar is still visible on screen. If I pull and refresh, then the loading progress goes away.

**Comment by anupsarode** [comment]
@cymcsg - My bad, in my above comment, I stated the NullPointerException was gone which was wrong. When disableLoadMore() is called, I get the following exception and the app crashes

```
07-27 21:00:23.698  10356-10356/com.myconpany.ps1 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mycompany.ps1, PID: 10356
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.marshalchen.ultimaterecyclerview.UltimateViewAdapter.swipeCustomLoadMoreView(android.view.View)' on a null object reference
            at com.marshalchen.ultimaterecyclerview.UltimateRecyclerView.disableLoadmore(UltimateRecyclerView.java:400)
            at com.mycompany.ps1.views.MainActivity.disableRecyclerViewLoadMore(MainActivity.java:408)
```

**Comment by cymcsg** [comment]
@anupsarode Do you set a null to the adatper and then call ``disableLoadMore``? I'll try to add judge the adapter at first.

**Comment by anupsarode** [comment]
@cymcsg - As of now, I'm not setting the adapter to null before calling disableLoadMore().

I tried clearing the adapter  (adapter.clear method) before calling disableLoadMore(). Still crashes.
I tried setting the adapter to null (adapter = null) before calling disableLoadMore(). Still crashes.

Here's what I'm trying to do.

- Initialize RecyclerView with enableLoadMore().
- Make a REST API call to return 10 records from database. If there are more than 10 records available, load more helps to get next 10 records.
- On getting the response, I find that there are only 2 records in the database.
- So I call disableLoadMore(). But the app crashes.

**Comment by hjw541988478** [comment]
same issue , how to solve this problem ?

**Comment by cymcsg** [comment]
Could you try the latest version 0.3.12 to test it? I think I need more details and test on it.Thank you very much.

**Comment by anupsarode** [comment]
@cymcsg - With the newer version, now the app doesn't crash. The only problem is, the load more animation still shows up. Can you please look into this matter?

**Comment by cymcsg** [comment]
Do you mean that the load more view shows after you disableloadmore ?

**Comment by hjw541988478** [comment]
@cymcsg absolutely.this is a bug.

**Comment by anupsarode** [comment]
Yes, the load more view still remains.

**Comment by cymcsg** [comment]
@hjw541988478  @anupsarode  I have tested in the demo to call ``disableloadmore`` and everything works fine. So could you show more details about this?

**Comment by anupsarode** [comment]
@cymcsg - I double checked my code and seems like it was an issue on my end. The load more view is gone. But seems like there is another issue now.

I setup recycler view with load more enabled. I then fire a query to load 10 items from database. There are 2 scenarios now.

1) REST Api response says, there are less than 10 items available. I disable loadmore and everything works great.

2) REST Api response says, there are more than 10 items available. Now the recycler view automatically scrolls to the 10th item in the list, shows the load more view and starts loading the other 10 items by making a REST Api call. (Basically, the loadMore() method which was set when setting up enableLoadMore is automatically called.) Expected behaviour is the list should not scroll automatically, and load more view should be shown only when the user scrolls to the bottom of the list.

Can you please look into this?

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue. @anupsarode @hjw541988478 @cymcsg
